
create external table tbl_orc(a int, b string, c int) partitioned by (d int) stored as orc;
describe formatted tbl_orc;
INSERT INTO tbl_orc (a, b, c) values(3, 'ccc', 12);
show partitions tbl_orc;
dfs -ls ${hiveconf:hive.metastore.warehouse.dir}/tbl_orc/;
alter table tbl_orc set default partition to 'random_partition';
describe formatted tbl_orc;
show partitions tbl_orc;
select * from tbl_orc;
select count(*) from tbl_orc;
INSERT INTO tbl_orc (a, b, c) values(4, 'ddd', 23);
show partitions tbl_orc;
select * from tbl_orc;
select count(*) from tbl_orc;
dfs -ls ${hiveconf:hive.metastore.warehouse.dir}/tbl_orc/;
drop table if exists tbl_orc;


create external table tbl_orc_2(a int, b string, c int) partitioned by (d int, e string, f bigint) stored as orc;
describe formatted tbl_orc_2;
INSERT INTO tbl_orc_2 (a, b, c) values(3, 'ccc', 12);
INSERT INTO tbl_orc_2 (a, b, c, d, e) values(5, 'ddd', 13, 32, 'tgf');
INSERT INTO tbl_orc_2 (a, b, c, e, f) values(6, 'eee', 14, 'tgh', 23456876);
show partitions tbl_orc_2;
dfs -ls ${hiveconf:hive.metastore.warehouse.dir}/tbl_orc_2/;
alter table tbl_orc_2 set default partition to 'default_partition';
describe formatted tbl_orc_2;
select * from tbl_orc_2;
select count(*) from tbl_orc_2;
show partitions tbl_orc_2;
INSERT INTO tbl_orc_2 (a, b, c) values(4, 'ddd', 23);
select * from tbl_orc_2;
select count(*) from tbl_orc_2;
show partitions tbl_orc_2;
dfs -ls ${hiveconf:hive.metastore.warehouse.dir}/tbl_orc_2/;
drop table if exists tbl_orc_2;


create external table tbl_orc_multiple(a int, b string, c int) partitioned by (d int, e string, f bigint) stored as orc location '${system:test.tmp.dir}/apps/hive/warehouse/test.db/tbl_orc_multiple/';
describe formatted tbl_orc_multiple;
INSERT INTO tbl_orc_multiple (a, b, c) values(3, 'ccc', 12);
INSERT INTO tbl_orc_multiple (a, b, c, d, e) values(5, 'ddd', 13, 32, 'tgf');
INSERT INTO tbl_orc_multiple (a, b, c, e, f) values(6, 'eee', 14, 'tgh', 23456876);
create external table tbl_orc_copy_multiple(a int, b string, c int) partitioned by (d int, e string, f bigint) stored as orc location '${system:test.tmp.dir}/apps/hive/warehouse/test.db/tbl_orc_multiple/';
show partitions tbl_orc_multiple;
msck repair table tbl_orc_copy_multiple;
show partitions tbl_orc_copy_multiple;
dfs -ls ${system:test.tmp.dir}/apps/hive/warehouse/test.db/tbl_orc_multiple/;
alter table tbl_orc_multiple set default partition to 'default_partition';
describe formatted tbl_orc_multiple;
select * from tbl_orc_multiple;
select count(*) from tbl_orc_multiple;
show partitions tbl_orc_multiple;
dfs -ls ${system:test.tmp.dir}/apps/hive/warehouse/test.db/tbl_orc_multiple/;
alter table tbl_orc_copy_multiple set default partition to 'default_partition';
describe formatted tbl_orc_copy_multiple;
select * from tbl_orc_copy_multiple;
select count(*) from tbl_orc_copy_multiple;
show partitions tbl_orc_copy_multiple;
drop table if exists tbl_orc_multiple;
drop table if exists tbl_orc_copy_multiple;
