set fs.default.name=invalidscheme:///;

CREATE TABLE table1_n5 (a STRING, b STRING) STORED AS TEXTFILE;
DESCRIBE table1_n5;
DESCRIBE EXTENDED table1_n5;

CREATE TABLE IF NOT EXISTS table1_n5 (a STRING, b STRING) STORED AS TEXTFILE;

CREATE TABLE IF NOT EXISTS table2_n2 (a STRING, b INT) STORED AS TEXTFILE;
DESCRIBE table2_n2;
DESCRIBE EXTENDED table2_n2;

CREATE TABLE table3 (a STRING, b STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
STORED AS TEXTFILE;
DESCRIBE table3;
DESCRIBE EXTENDED table3;

CREATE TABLE table4 (a STRING, b STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
STORED AS SEQUENCEFILE;
DESCRIBE table4;
DESCRIBE EXTENDED table4;

CREATE TABLE table5_n1 (a STRING, b STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
STORED AS RCFILE;
DESCRIBE table5_n1;
DESCRIBE EXTENDED table5_n1;
