CREATE TABLE table1_n11 (a STRING, b STRING, PRIMARY KEY (a) NOT ENFORCED);
CREATE TABLE table2_n7 (a STRING, b STRING, PRIMARY KEY (a) NOT ENFORCED RELY);

DESCRIBE EXTENDED table1_n11;
DESCRIBE EXTENDED table2_n7;

DESCRIBE FORMATTED table1_n11;
DESCRIBE FORMATTED table2_n7;
