EXPLAIN CREATE DATABASE d;
CREATE DATABASE d;

EXPLAIN SHOW DATABASES;
SHOW DATABASES;

EXPLAIN DESCRIBE DATABASE d;
DESCRIBE DATABASE d;

EXPLAIN ALTER DATABASE d SET dbproperties('test'='yesthisis');
ALTER DATABASE d SET dbproperties('test'='yesthisis');

EXPLAIN SHOW CREATE DATABASE d;
SHOW CREATE DATABASE d;

EXPLAIN USE d;
USE d;

EXPLAIN DROP DATABASE d;
DROP DATABASE d;
