DROP TABLE IF EXISTS DECIMAL;

CREATE TABLE DECIMAL (dec decimal);

LOAD DATA LOCAL INPATH '../../data/files/decimal_10_0.txt' OVERWRITE INTO TABLE DECIMAL;

SELECT dec FROM DECIMAL;

DROP TABLE DECIMAL;