DROP TABLE IF EXISTS `DECIMAL_n0`;

CREATE TABLE `DECIMAL_n0` (`dec` decimal);

LOAD DATA LOCAL INPATH '../../data/files/decimal_10_0.txt' OVERWRITE INTO TABLE `DECIMAL_n0`;

SELECT `dec` FROM `DECIMAL_n0`;

DROP TABLE `DECIMAL_n0`;
