EXPLAIN DESC FUNCTION replace;
DESC FUNCTION replace;

EXPLAIN DESC FUNCTION EXTENDED replace;
DESC FUNCTION EXTENDED replace;

DESCRIBE FUNCTION dense_rank;
DESCRIBE FUNCTION EXTENDED dense_rank;

DESCRIBE FUNCTION surrogate_key;
DESCRIBE FUNCTION EXTENDED surrogate_key;
