--! qt:dataset:src1
CREATE TABLE dest1_n159(value STRING, key INT) STORED AS TEXTFILE;

EXPLAIN
FROM src1
INSERT OVERWRITE TABLE dest1_n159 SELECT NULL, src1.key where NULL = NULL;

FROM src1
INSERT OVERWRITE TABLE dest1_n159 SELECT NULL, src1.key where NULL = NULL;

SELECT dest1_n159.* FROM dest1_n159;

