CREATE TABLE IF NOT EXISTS t1(c0 boolean, c1 boolean);

Explain SELECT SUM(1) FROM t1;

SELECT SUM(1) FROM t1;

SELECT COUNT(*) FROM t1;

INSERT INTO TABLE t1 VALUES (true, false), (false, true);

SELECT SUM(1) FROM t1;

SELECT COUNT(*) FROM t1;