CREATE TABLE t (a INT);

EXPLAIN ALTER TABLE t SET TBLPROPERTIES('a'='x', 'b'='y');
ALTER TABLE t SET TBLPROPERTIES('a'='x', 'b'='y');
SHOW CREATE TABLE t;
EXPLAIN ALTER TABLE t UNSET TBLPROPERTIES('a', 'b');
ALTER TABLE t UNSET TBLPROPERTIES('a', 'b');
SHOW CREATE TABLE t;
