EXPLAIN SHOW FUNCTIONS;
SHOW FUNCTIONS;

EXPLAIN SHOW FUNCTIONS LIKE 'c%';
SHOW FUNCTIONS LIKE 'c%';

SHOW FUNCTIONS LIKE '%e';

SHOW FUNCTIONS LIKE 'log%';

SHOW FUNCTIONS LIKE '%date%';

SHOW FUNCTIONS LIKE '%%%';

EXPLAIN SHOW FUNCTIONS LIKE 'When';
SHOW FUNCTIONS LIKE 'When';

SHOW FUNCTIONS LIKE 'max|min';

SHOW FUNCTIONS LIKE 'xpath%|m%';

SHOW FUNCTIONS LIKE 'nomatch';

SHOW FUNCTIONS LIKE "log";

SHOW FUNCTIONS LIKE 'log';

SHOW FUNCTIONS LIKE `log`;

SHOW FUNCTIONS LIKE 'log%';

SHOW FUNCTIONS LIKE "log%";

SHOW FUNCTIONS LIKE `log%`;
