--! qt:dataset::ONLY

SET hive.ddl.output.format=json;
SET hive.cli.errors.ignore=true;
SET hive.test.authz.sstd.hs2.mode=true;

SHOW DATABASES;
DESC DATABASE default;

CREATE TABLE t (i int);
SHOW TABLES;
SHOW EXTENDED TABLES;
SHOW TABLE EXTENDED LIKE 't';
DESC t;

CREATE VIEW v AS SELECT * FROM t;
SHOW VIEWS;

CREATE MATERIALIZED VIEW mv DISABLE REWRITE AS SELECT * FROM t;
SHOW MATERIALIZED VIEWS;

CREATE RESOURCE PLAN rp;
SHOW RESOURCE PLANS;
SHOW RESOURCE PLAN rp;
ALTER RESOURCE PLAN rp VALIDATE;
