DESCRIBE FUNCTION std;
DESCRIBE FUNCTION EXTENDED std;

DESCRIBE FUNCTION stddev;
DESCRIBE FUNCTION EXTENDED stddev;

DESCRIBE FUNCTION stddev_pop;
DESCRIBE FUNCTION EXTENDED stddev_pop;
DESCRIBE FUNCTION std;
DESCRIBE FUNCTION EXTENDED std;

DESCRIBE FUNCTION stddev;
DESCRIBE FUNCTION EXTENDED stddev;

DESCRIBE FUNCTION stddev_pop;
DESCRIBE FUNCTION EXTENDED stddev_pop;
