CREATE TABLE mssql_t1 (
  d1   DATETIME,
  nc1  NCHAR(10),
  n1   NUMERIC(3,0),
  n2   NUMERIC(3),
  n3   NUMERIC,
  v1   VARCHAR(MAX),
  nv1  NVARCHAR(10),
  nv2  NVARCHAR(MAX)
);

CREATE TABLE [mssql_t2](
 [i1] [INT] IDENTITY(1,1) NOT NULL,
 [v1] [VARCHAR](350) NULL,
 [v2] [VARCHAR](max) NULL,
 [b1] [BIT] NULL,
 [d1] [DATETIME] NULL,
 CONSTRAINT [PK_i1] PRIMARY KEY CLUSTERED ([i1] ASC) 
   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]; 

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [default].[mssql_t3](
 [v1]  [VARCHAR](50) NOT NULL,
 [s2]  [SMALLINT] NULL,
 [sd1] [SMALLDATETIME] NULL,
 [i1]  [INT] NULL,
 [v2]  [VARCHAR](100) NULL,
 CONSTRAINT [PK_v1] PRIMARY KEY CLUSTERED ([v1] ASC) 
   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_PADDING OFF
GO 