-- Licensed to the Apache Software Foundation (ASF) under one
-- or more contributor license agreements. See the NOTICE file
-- distributed with this work for additional information
-- regarding copyright ownership. The ASF licenses this file
-- to you under the Apache License, Version 2.0 (the
-- "License"); you may not use this file except in compliance
-- with the License. You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and

    

-- Rebuilds all HMS standalone indexes on PostgreSQL.
-- Update this file whenever a new upgrade script adds an index.

DROP INDEX IF EXISTS "NOTIFICATION_LOG_EVENT_ID";
CREATE UNIQUE INDEX "NOTIFICATION_LOG_EVENT_ID" ON "NOTIFICATION_LOG" USING btree ("EVENT_ID");

DROP INDEX IF EXISTS "BUCKETING_COLS_N49";
CREATE INDEX "BUCKETING_COLS_N49" ON "BUCKETING_COLS" USING btree ("SD_ID");

DROP INDEX IF EXISTS "DATABASE_PARAMS_N49";
CREATE INDEX "DATABASE_PARAMS_N49" ON "DATABASE_PARAMS" USING btree ("DB_ID");

DROP INDEX IF EXISTS "DB_PRIVS_N49";
CREATE INDEX "DB_PRIVS_N49" ON "DB_PRIVS" USING btree ("DB_ID");

DROP INDEX IF EXISTS "DC_PRIVS_N49";
CREATE INDEX "DC_PRIVS_N49" ON "DC_PRIVS" USING btree ("NAME");

DROP INDEX IF EXISTS "PARTITIONCOLUMNPRIVILEGEINDEX";
CREATE INDEX "PARTITIONCOLUMNPRIVILEGEINDEX" ON "PART_COL_PRIVS" USING btree ("AUTHORIZER", "PART_ID", "COLUMN_NAME", "PRINCIPAL_NAME", "PRINCIPAL_TYPE", "PART_COL_PRIV", "GRANTOR", "GRANTOR_TYPE");

DROP INDEX IF EXISTS "PARTITIONEVENTINDEX";
CREATE INDEX "PARTITIONEVENTINDEX" ON "PARTITION_EVENTS" USING btree ("PARTITION_NAME");

DROP INDEX IF EXISTS "PARTITIONS_N50";
CREATE INDEX "PARTITIONS_N50" ON "PARTITIONS" USING btree ("SD_ID");

DROP INDEX IF EXISTS "PARTITION_KEYS_N49";
CREATE INDEX "PARTITION_KEYS_N49" ON "PARTITION_KEYS" USING btree ("TBL_ID");

DROP INDEX IF EXISTS "PARTITION_KEY_VALS_N49";
CREATE INDEX "PARTITION_KEY_VALS_N49" ON "PARTITION_KEY_VALS" USING btree ("PART_ID");

DROP INDEX IF EXISTS "PARTITION_PARAMS_N49";
CREATE INDEX "PARTITION_PARAMS_N49" ON "PARTITION_PARAMS" USING btree ("PART_ID");

DROP INDEX IF EXISTS "PARTPRIVILEGEINDEX";
CREATE INDEX "PARTPRIVILEGEINDEX" ON "PART_PRIVS" USING btree ("AUTHORIZER", "PART_ID", "PRINCIPAL_NAME", "PRINCIPAL_TYPE", "PART_PRIV", "GRANTOR", "GRANTOR_TYPE");

DROP INDEX IF EXISTS "PART_COL_PRIVS_N49";
CREATE INDEX "PART_COL_PRIVS_N49" ON "PART_COL_PRIVS" USING btree ("PART_ID");

DROP INDEX IF EXISTS "PART_PRIVS_N49";
CREATE INDEX "PART_PRIVS_N49" ON "PART_PRIVS" USING btree ("PART_ID");

DROP INDEX IF EXISTS "PCS_STATS_IDX";
CREATE INDEX "PCS_STATS_IDX" ON "PART_COL_STATS" USING btree ("PART_ID","COLUMN_NAME");

DROP INDEX IF EXISTS "ROLE_MAP_N49";
CREATE INDEX "ROLE_MAP_N49" ON "ROLE_MAP" USING btree ("ROLE_ID");

DROP INDEX IF EXISTS "SDS_N49";
CREATE INDEX "SDS_N49" ON "SDS" USING btree ("SERDE_ID");

DROP INDEX IF EXISTS "SDS_N50";
CREATE INDEX "SDS_N50" ON "SDS" USING btree ("CD_ID");

DROP INDEX IF EXISTS "SD_PARAMS_N49";
CREATE INDEX "SD_PARAMS_N49" ON "SD_PARAMS" USING btree ("SD_ID");

DROP INDEX IF EXISTS "SERDE_PARAMS_N49";
CREATE INDEX "SERDE_PARAMS_N49" ON "SERDE_PARAMS" USING btree ("SERDE_ID");

DROP INDEX IF EXISTS "SORT_COLS_N49";
CREATE INDEX "SORT_COLS_N49" ON "SORT_COLS" USING btree ("SD_ID");

DROP INDEX IF EXISTS "TABLECOLUMNPRIVILEGEINDEX";
CREATE INDEX "TABLECOLUMNPRIVILEGEINDEX" ON "TBL_COL_PRIVS" USING btree ("AUTHORIZER", "TBL_ID", "COLUMN_NAME", "PRINCIPAL_NAME", "PRINCIPAL_TYPE", "TBL_COL_PRIV", "GRANTOR", "GRANTOR_TYPE");

DROP INDEX IF EXISTS "TABLEPRIVILEGEINDEX";
CREATE INDEX "TABLEPRIVILEGEINDEX" ON "TBL_PRIVS" USING btree ("AUTHORIZER", "TBL_ID", "PRINCIPAL_NAME", "PRINCIPAL_TYPE", "TBL_PRIV", "GRANTOR", "GRANTOR_TYPE");

DROP INDEX IF EXISTS "TABLE_PARAMS_N49";
CREATE INDEX "TABLE_PARAMS_N49" ON "TABLE_PARAMS" USING btree ("TBL_ID");

DROP INDEX IF EXISTS "TBLS_N50";
CREATE INDEX "TBLS_N50" ON "TBLS" USING btree ("SD_ID");

DROP INDEX IF EXISTS "TBL_COL_PRIVS_N49";
CREATE INDEX "TBL_COL_PRIVS_N49" ON "TBL_COL_PRIVS" USING btree ("TBL_ID");

DROP INDEX IF EXISTS "TAB_COL_STATS_IDX";
CREATE INDEX "TAB_COL_STATS_IDX" ON "TAB_COL_STATS" USING btree ("TBL_ID","COLUMN_NAME");

DROP INDEX IF EXISTS "TBL_PRIVS_N49";
CREATE INDEX "TBL_PRIVS_N49" ON "TBL_PRIVS" USING btree ("TBL_ID");

DROP INDEX IF EXISTS "TYPE_FIELDS_N49";
CREATE INDEX "TYPE_FIELDS_N49" ON "TYPE_FIELDS" USING btree ("TYPE_NAME");

DROP INDEX IF EXISTS "UNIQUEFUNCTION";
CREATE UNIQUE INDEX "UNIQUEFUNCTION" ON "FUNCS" ("FUNC_NAME", "DB_ID");

DROP INDEX IF EXISTS "FUNCS_N49";
CREATE INDEX "FUNCS_N49" ON "FUNCS" ("DB_ID");

DROP INDEX IF EXISTS "FUNC_RU_N49";
CREATE INDEX "FUNC_RU_N49" ON "FUNC_RU" ("FUNC_ID");

DROP INDEX IF EXISTS "CONSTRAINTS_PARENT_TBLID_INDEX";
CREATE INDEX "CONSTRAINTS_PARENT_TBLID_INDEX" ON "KEY_CONSTRAINTS" USING BTREE ("PARENT_TBL_ID");

DROP INDEX IF EXISTS "CONSTRAINTS_CONSTRAINT_TYPE_INDEX";
CREATE INDEX "CONSTRAINTS_CONSTRAINT_TYPE_INDEX" ON "KEY_CONSTRAINTS" USING BTREE ("CONSTRAINT_TYPE");

DROP INDEX IF EXISTS "MV_UNIQUE_TABLE";
CREATE INDEX "MV_UNIQUE_TABLE"
    ON "MV_CREATION_METADATA" USING btree ("TBL_NAME", "DB_NAME");

DROP INDEX IF EXISTS TC_TXNID_INDEX;
CREATE INDEX TC_TXNID_INDEX ON "TXN_COMPONENTS" USING hash ("TC_TXNID");

DROP INDEX IF EXISTS COMPLETED_TXN_COMPONENTS_INDEX;
CREATE INDEX COMPLETED_TXN_COMPONENTS_INDEX ON "COMPLETED_TXN_COMPONENTS" USING btree ("CTC_DATABASE", "CTC_TABLE", "CTC_PARTITION");

DROP INDEX IF EXISTS HL_TXNID_INDEX;
CREATE INDEX HL_TXNID_INDEX ON "HIVE_LOCKS" USING hash ("HL_TXNID");

DROP INDEX IF EXISTS "COMPLETED_COMPACTIONS_RES";
CREATE INDEX "COMPLETED_COMPACTIONS_RES" ON "COMPLETED_COMPACTIONS" ("CC_DATABASE","CC_TABLE","CC_PARTITION");

DROP INDEX IF EXISTS "TBL_TO_TXN_ID_IDX";
CREATE UNIQUE INDEX "TBL_TO_TXN_ID_IDX" ON "TXN_TO_WRITE_ID" ("T2W_DATABASE", "T2W_TABLE", "T2W_TXNID");

DROP INDEX IF EXISTS "TBL_TO_WRITE_ID_IDX";
CREATE UNIQUE INDEX "TBL_TO_WRITE_ID_IDX" ON "TXN_TO_WRITE_ID" ("T2W_DATABASE", "T2W_TABLE", "T2W_WRITEID");

DROP INDEX IF EXISTS "NEXT_WRITE_ID_IDX";
CREATE UNIQUE INDEX "NEXT_WRITE_ID_IDX" ON "NEXT_WRITE_ID" ("NWI_DATABASE", "NWI_TABLE");

DROP INDEX IF EXISTS "MIN_HISTORY_WRITE_ID_IDX";
CREATE INDEX "MIN_HISTORY_WRITE_ID_IDX" ON "MIN_HISTORY_WRITE_ID" ("MH_DATABASE", "MH_TABLE", "MH_WRITEID");

DROP INDEX IF EXISTS "MIN_HISTORY_LEVEL_IDX";
CREATE INDEX "MIN_HISTORY_LEVEL_IDX" ON "MIN_HISTORY_LEVEL" ("MHL_MIN_OPEN_TXNID");

DROP INDEX IF EXISTS "IDX_RUNTIME_STATS_CREATE_TIME";
CREATE INDEX "IDX_RUNTIME_STATS_CREATE_TIME" ON "RUNTIME_STATS" ("CREATE_TIME");

DROP INDEX IF EXISTS IDX_SCHEDULED_EXECUTIONS_LAST_UPDATE_TIME;
CREATE INDEX IDX_SCHEDULED_EXECUTIONS_LAST_UPDATE_TIME ON "SCHEDULED_EXECUTIONS" ("LAST_UPDATE_TIME");

DROP INDEX IF EXISTS IDX_SCHEDULED_EXECUTIONS_SCHEDULED_QUERY_ID;
CREATE INDEX IDX_SCHEDULED_EXECUTIONS_SCHEDULED_QUERY_ID ON "SCHEDULED_EXECUTIONS" ("SCHEDULED_QUERY_ID");

DROP INDEX IF EXISTS UNIQUE_SCHEDULED_EXECUTIONS_ID;
CREATE UNIQUE INDEX UNIQUE_SCHEDULED_EXECUTIONS_ID ON "SCHEDULED_EXECUTIONS" ("SCHEDULED_EXECUTION_ID");

DROP INDEX IF EXISTS "POLICY_IDX";
CREATE INDEX "POLICY_IDX" ON "REPLICATION_METRICS" ("RM_POLICY");

DROP INDEX IF EXISTS "DUMP_IDX";
CREATE INDEX "DUMP_IDX" ON "REPLICATION_METRICS" ("RM_DUMP_EXECUTION_ID");

DROP INDEX IF EXISTS "UNIQUESTOREDPROC";
CREATE UNIQUE INDEX "UNIQUESTOREDPROC" ON "STORED_PROCS" ("NAME", "DB_ID");

DROP INDEX IF EXISTS "UNIQUEPKG";
CREATE UNIQUE INDEX "UNIQUEPKG" ON "PACKAGES" ("NAME", "DB_ID");


