SELECT 'Upgrading MetaStore schema from 4.2.0 to 4.3.0';

ALTER TABLE "HIVE_LOCKS" ADD COLUMN "HL_CATALOG" varchar(128) NOT NULL DEFAULT 'hive';
ALTER TABLE "MATERIALIZATION_REBUILD_LOCKS" ADD COLUMN "MRL_CAT_NAME" varchar(128) NOT NULL DEFAULT 'hive';

CREATE INDEX "MIN_HISTORY_WRITE_ID_IDX" ON "MIN_HISTORY_WRITE_ID" ("MH_DATABASE", "MH_TABLE", "MH_WRITEID");

-- Add surrogate primary keys for HA database replication. For large transactional
-- tables, add the column without a default first, backfill via sequence, then set
-- NOT NULL and add the PK. This avoids the long ACCESS EXCLUSIVE table rewrite that
-- ADD COLUMN ... bigserial PRIMARY KEY takes on populated tables. Counter tables
-- contain a single row and keep the one-step form. Plan a maintenance window
-- for busy metastores as backfill duration scales with TXN_COMPONENTS/WRITE_SET row counts.

ALTER TABLE "TXN_COMPONENTS" ADD COLUMN "TC_ID" bigint;
CREATE SEQUENCE "TXN_COMPONENTS_TC_ID_seq" OWNED BY "TXN_COMPONENTS"."TC_ID";
UPDATE "TXN_COMPONENTS" SET "TC_ID" = nextval('"TXN_COMPONENTS_TC_ID_seq"') WHERE "TC_ID" IS NULL;
ALTER TABLE "TXN_COMPONENTS" ALTER COLUMN "TC_ID" SET DEFAULT nextval('"TXN_COMPONENTS_TC_ID_seq"');
ALTER TABLE "TXN_COMPONENTS" ALTER COLUMN "TC_ID" SET NOT NULL;
ALTER TABLE "TXN_COMPONENTS" ADD CONSTRAINT "TXN_COMPONENTS_pkey" PRIMARY KEY ("TC_ID");

ALTER TABLE "COMPLETED_TXN_COMPONENTS" ADD COLUMN "CTC_ID" bigint;
CREATE SEQUENCE "COMPLETED_TXN_COMPONENTS_CTC_ID_seq" OWNED BY "COMPLETED_TXN_COMPONENTS"."CTC_ID";
UPDATE "COMPLETED_TXN_COMPONENTS" SET "CTC_ID" = nextval('"COMPLETED_TXN_COMPONENTS_CTC_ID_seq"') WHERE "CTC_ID" IS NULL;
ALTER TABLE "COMPLETED_TXN_COMPONENTS" ALTER COLUMN "CTC_ID" SET DEFAULT nextval('"COMPLETED_TXN_COMPONENTS_CTC_ID_seq"');
ALTER TABLE "COMPLETED_TXN_COMPONENTS" ALTER COLUMN "CTC_ID" SET NOT NULL;
ALTER TABLE "COMPLETED_TXN_COMPONENTS" ADD CONSTRAINT "COMPLETED_TXN_COMPONENTS_pkey" PRIMARY KEY ("CTC_ID");

ALTER TABLE "COMPACTION_METRICS_CACHE" ADD COLUMN "CMC_ID" bigint;
CREATE SEQUENCE "COMPACTION_METRICS_CACHE_CMC_ID_seq" OWNED BY "COMPACTION_METRICS_CACHE"."CMC_ID";
UPDATE "COMPACTION_METRICS_CACHE" SET "CMC_ID" = nextval('"COMPACTION_METRICS_CACHE_CMC_ID_seq"') WHERE "CMC_ID" IS NULL;
ALTER TABLE "COMPACTION_METRICS_CACHE" ALTER COLUMN "CMC_ID" SET DEFAULT nextval('"COMPACTION_METRICS_CACHE_CMC_ID_seq"');
ALTER TABLE "COMPACTION_METRICS_CACHE" ALTER COLUMN "CMC_ID" SET NOT NULL;
ALTER TABLE "COMPACTION_METRICS_CACHE" ADD CONSTRAINT "COMPACTION_METRICS_CACHE_pkey" PRIMARY KEY ("CMC_ID");

ALTER TABLE "WRITE_SET" ADD COLUMN "WS_ID" bigint;
CREATE SEQUENCE "WRITE_SET_WS_ID_seq" OWNED BY "WRITE_SET"."WS_ID";
UPDATE "WRITE_SET" SET "WS_ID" = nextval('"WRITE_SET_WS_ID_seq"') WHERE "WS_ID" IS NULL;
ALTER TABLE "WRITE_SET" ALTER COLUMN "WS_ID" SET DEFAULT nextval('"WRITE_SET_WS_ID_seq"');
ALTER TABLE "WRITE_SET" ALTER COLUMN "WS_ID" SET NOT NULL;
ALTER TABLE "WRITE_SET" ADD CONSTRAINT "WRITE_SET_pkey" PRIMARY KEY ("WS_ID");

DROP INDEX IF EXISTS tbl_to_txn_id_idx;
DROP INDEX IF EXISTS "TBL_TO_TXN_ID_IDX";
ALTER TABLE "TXN_TO_WRITE_ID" ADD PRIMARY KEY ("T2W_DATABASE", "T2W_TABLE", "T2W_TXNID");

DROP INDEX IF EXISTS next_write_id_idx;
DROP INDEX IF EXISTS "NEXT_WRITE_ID_IDX";
ALTER TABLE "NEXT_WRITE_ID" ADD PRIMARY KEY ("NWI_DATABASE", "NWI_TABLE");

ALTER TABLE "MIN_HISTORY_WRITE_ID" ADD COLUMN "MH_ID" bigint;
CREATE SEQUENCE "MIN_HISTORY_WRITE_ID_MH_ID_seq" OWNED BY "MIN_HISTORY_WRITE_ID"."MH_ID";
UPDATE "MIN_HISTORY_WRITE_ID" SET "MH_ID" = nextval('"MIN_HISTORY_WRITE_ID_MH_ID_seq"') WHERE "MH_ID" IS NULL;
ALTER TABLE "MIN_HISTORY_WRITE_ID" ALTER COLUMN "MH_ID" SET DEFAULT nextval('"MIN_HISTORY_WRITE_ID_MH_ID_seq"');
ALTER TABLE "MIN_HISTORY_WRITE_ID" ALTER COLUMN "MH_ID" SET NOT NULL;
ALTER TABLE "MIN_HISTORY_WRITE_ID" ADD CONSTRAINT "MIN_HISTORY_WRITE_ID_pkey" PRIMARY KEY ("MH_ID");

ALTER TABLE "TXN_LOCK_TBL" ADD COLUMN "TLT_ID" bigserial PRIMARY KEY;
ALTER TABLE "NEXT_LOCK_ID" ADD COLUMN "NL_ID" bigserial PRIMARY KEY;
ALTER TABLE "NEXT_COMPACTION_QUEUE_ID" ADD COLUMN "NCQI_ID" bigserial PRIMARY KEY;

-- These lines need to be last. Insert any changes above.
UPDATE "VERSION" SET "SCHEMA_VERSION"='4.3.0', "VERSION_COMMENT"='Hive release version 4.3.0' where "VER_ID"=1;
SELECT 'Finished upgrading MetaStore schema from 4.2.0 to 4.3.0';
