SELECT 'Upgrading MetaStore schema from 4.2.0 to 4.3.0';

DROP INDEX COMPLETED_TXN_COMPONENTS_INDEX;
DROP INDEX "COMPLETED_COMPACTIONS_RES";
DROP INDEX "TBL_TO_TXN_ID_IDX";
DROP INDEX "TBL_TO_WRITE_ID_IDX";
DROP INDEX "NEXT_WRITE_ID_IDX";

ALTER TABLE "HIVE_LOCKS" ADD COLUMN "HL_CATALOG" varchar(128) NOT NULL DEFAULT 'hive';
ALTER TABLE "MATERIALIZATION_REBUILD_LOCKS" ADD COLUMN "MRL_CAT_NAME" varchar(128) NOT NULL DEFAULT 'hive';
ALTER TABLE "TXN_COMPONENTS" ADD COLUMN "TC_CATALOG" varchar(128) NOT NULL DEFAULT 'hive';
ALTER TABLE "COMPLETED_TXN_COMPONENTS" ADD COLUMN "CTC_CATALOG" varchar(128) NOT NULL DEFAULT 'hive';
ALTER TABLE "COMPACTION_QUEUE" ADD COLUMN "CQ_CATALOG" varchar(128) NOT NULL DEFAULT 'hive';
ALTER TABLE "COMPLETED_COMPACTIONS" ADD COLUMN "CC_CATALOG" varchar(128) NOT NULL DEFAULT 'hive';
ALTER TABLE "COMPACTION_METRICS_CACHE" ADD COLUMN "CMC_CATALOG" varchar(128) NOT NULL DEFAULT 'hive';
ALTER TABLE "WRITE_SET" ADD COLUMN "WS_CATALOG" varchar(128) NOT NULL DEFAULT 'hive';
ALTER TABLE "TXN_TO_WRITE_ID" ADD COLUMN "T2W_CATALOG" varchar(128) NOT NULL DEFAULT 'hive';
ALTER TABLE "NEXT_WRITE_ID" ADD COLUMN "NWI_CATALOG" varchar(128) NOT NULL DEFAULT 'hive';
ALTER TABLE "MIN_HISTORY_WRITE_ID" ADD COLUMN "MH_CATALOG" varchar(128) NOT NULL DEFAULT 'hive';
ALTER TABLE "TXN_WRITE_NOTIFICATION_LOG" ADD COLUMN "WNL_CATALOG" varchar(128) NOT NULL DEFAULT 'hive';

CREATE INDEX COMPLETED_TXN_COMPONENTS_INDEX ON "COMPLETED_TXN_COMPONENTS" USING btree ("CTC_CATALOG", "CTC_DATABASE", "CTC_TABLE", "CTC_PARTITION");
CREATE INDEX "COMPLETED_COMPACTIONS_RES" ON "COMPLETED_COMPACTIONS" ("CC_CATALOG", "CC_DATABASE", "CC_TABLE", "CC_PARTITION");
CREATE UNIQUE INDEX "TBL_TO_TXN_ID_IDX" ON "TXN_TO_WRITE_ID" ("T2W_CATALOG", "T2W_DATABASE", "T2W_TABLE", "T2W_TXNID");
CREATE UNIQUE INDEX "TBL_TO_WRITE_ID_IDX" ON "TXN_TO_WRITE_ID" ("T2W_CATALOG", "T2W_DATABASE", "T2W_TABLE", "T2W_WRITEID");
CREATE UNIQUE INDEX "NEXT_WRITE_ID_IDX" ON "NEXT_WRITE_ID" ("NWI_CATALOG", "NWI_DATABASE", "NWI_TABLE");
CREATE INDEX "MIN_HISTORY_WRITE_ID_IDX" ON "MIN_HISTORY_WRITE_ID" ("MH_CATALOG", "MH_DATABASE", "MH_TABLE", "MH_WRITEID");

-- These lines need to be last. Insert any changes above.
UPDATE "VERSION" SET "SCHEMA_VERSION"='4.3.0', "VERSION_COMMENT"='Hive release version 4.3.0' where "VER_ID"=1;
SELECT 'Finished upgrading MetaStore schema from 4.2.0 to 4.3.0';
