SELECT 'Upgrading MetaStore schema from 4.2.0 to 4.3.0';

ALTER TABLE "HIVE_LOCKS" ADD COLUMN "HL_CATALOG" varchar(128) NOT NULL DEFAULT 'hive';
ALTER TABLE "MATERIALIZATION_REBUILD_LOCKS" ADD COLUMN "MRL_CAT_NAME" varchar(128) NOT NULL DEFAULT 'hive';

CREATE INDEX "MIN_HISTORY_WRITE_ID_IDX" ON "MIN_HISTORY_WRITE_ID" ("MH_DATABASE", "MH_TABLE", "MH_WRITEID");

ALTER TABLE "TXN_COMPONENTS" ADD COLUMN "TC_ID" bigserial PRIMARY KEY;
ALTER TABLE "COMPLETED_TXN_COMPONENTS" ADD COLUMN "CTC_ID" bigserial PRIMARY KEY;
ALTER TABLE "COMPACTION_METRICS_CACHE" ADD COLUMN "CMC_ID" bigserial PRIMARY KEY;
ALTER TABLE "WRITE_SET" ADD COLUMN "WS_ID" bigserial PRIMARY KEY;

DROP INDEX "TBL_TO_TXN_ID_IDX";
ALTER TABLE "TXN_TO_WRITE_ID" ADD PRIMARY KEY ("T2W_DATABASE", "T2W_TABLE", "T2W_TXNID");

DROP INDEX "NEXT_WRITE_ID_IDX";
ALTER TABLE "NEXT_WRITE_ID" ADD PRIMARY KEY ("NWI_DATABASE", "NWI_TABLE");

ALTER TABLE "MIN_HISTORY_WRITE_ID" ADD PRIMARY KEY ("MH_TXNID", "MH_DATABASE", "MH_TABLE", "MH_WRITEID");

ALTER TABLE "TXN_LOCK_TBL" ADD COLUMN "TLT_ID" bigserial PRIMARY KEY;
ALTER TABLE "NEXT_LOCK_ID" ADD COLUMN "NL_ID" bigserial PRIMARY KEY;
ALTER TABLE "NEXT_COMPACTION_QUEUE_ID" ADD COLUMN "NCQI_ID" bigserial PRIMARY KEY;

-- These lines need to be last. Insert any changes above.
UPDATE "VERSION" SET "SCHEMA_VERSION"='4.3.0', "VERSION_COMMENT"='Hive release version 4.3.0' where "VER_ID"=1;
SELECT 'Finished upgrading MetaStore schema from 4.2.0 to 4.3.0';
