CREATE TABLE "APP"."CDH_VERSION" ("VER_ID" BIGINT NOT NULL, "SCHEMA_VERSION" VARCHAR(127) NOT NULL, "VERSION_COMMENT" VARCHAR(255));

ALTER TABLE "APP"."CDH_VERSION" ADD CONSTRAINT "CDH_VERSION_PK" PRIMARY KEY ("VER_ID");

INSERT INTO "APP"."CDH_VERSION" (VER_ID, SCHEMA_VERSION, VERSION_COMMENT) VALUES (1, '3.1.3000.7.1.0.0', 'Hive release version 3.1.3000 for CDH 7.1.0.0');