-- Upgrade MetaStore schema from 3.1.0 to 3.1.1000

-- HIVE-20221: change PARTITION_PARAMS.PARAM_VALUE to CLOB
ALTER TABLE "APP"."PARTITION_PARAMS" ADD COLUMN "PARAM_VALUE_CLOB" CLOB;
UPDATE "APP"."PARTITION_PARAMS" SET PARAM_VALUE_CLOB=CAST(PARAM_VALUE AS CLOB);
ALTER TABLE "APP"."PARTITION_PARAMS" DROP COLUMN PARAM_VALUE;
RENAME COLUMN "APP"."PARTITION_PARAMS"."PARAM_VALUE_CLOB" TO "PARAM_VALUE";

-- This needs to be the last thing done.  Insert any changes above this line.
UPDATE "APP".VERSION SET SCHEMA_VERSION='3.1.1000', VERSION_COMMENT='Hive release version 3.1.1000' where VER_ID=1;
