
ALTER TABLE "APP"."TAB_COL_STATS" ADD COLUMN "ENGINE" VARCHAR(128);
ALTER TABLE "APP"."TAB_COL_STATS" ALTER COLUMN "ENGINE" NOT NULL;
ALTER TABLE "APP"."PART_COL_STATS" ADD "ENGINE" VARCHAR(128);
ALTER TABLE "APP"."PART_COL_STATS" ALTER COLUMN "ENGINE" NOT NULL;

-- These lines need to be last.  Insert any changes above.
UPDATE "APP".VERSION SET SCHEMA_VERSION='3.1.2000', VERSION_COMMENT='Hive release version 3.1.2000' where VER_ID=1;

