---
# thrift changes
'*.thrift':
  - kgyrtkirk
# parser changes
'*.g':
  - kgyrtkirk
# metastore database changes
'package.jdo':
  - kgyrtkirk
# these will match on various scheduled query
'*(schq|Scheduled)*':
  - kgyrtkirk
'**/schq/**':
  - kgyrtkirk
# these will match sketches related stuff
'*[sS]ketches*':
  - kgyrtkirk
# Build system
'Jenkinsfile':
  - kgyrtkirk
# ddl changes
'**/ddl/**':
  - miklosgergely
# driver related changes
'**/ql/(*Driver*|Compiler|Executor).java':
  - miklosgergely
# schematool changes
'**schematool**':
  - miklosgergely
# metatool changes
'**metatool**':
  - miklosgergely
  
