SELECT 'Upgrading MetaStore schema from 1.2.1000 to 2.0.0' AS Status from dual;

--@022-HIVE-11970.oracle.sql;
ALTER TABLE COLUMNS_V2 MODIFY (
  "COLUMN_NAME" VARCHAR2(1000)
);

ALTER TABLE PART_COL_PRIVS MODIFY (
  "COLUMN_NAME" VARCHAR2(1000)
);

ALTER TABLE TBL_COL_PRIVS MODIFY (
  "COLUMN_NAME" VARCHAR2(1000)
);

ALTER TABLE SORT_COLS MODIFY (
  "COLUMN_NAME" VARCHAR2(1000)
);

ALTER TABLE TAB_COL_STATS MODIFY (
  "COLUMN_NAME" VARCHAR2(1000)
);

ALTER TABLE PART_COL_STATS MODIFY (
  "COLUMN_NAME" VARCHAR2(1000)
);

UPDATE VERSION SET SCHEMA_VERSION='2.0.0', VERSION_COMMENT='Hive release version 2.0.0' where VER_ID=1;
SELECT 'Finished upgrading MetaStore schema from 1.2.1000 to 2.0.0' AS Status from dual;
