SELECT 'Upgrading MetaStore schema from 3.0.0 to 3.1.0' AS Status from dual;

-- HIVE-19440
ALTER TABLE GLOBAL_PRIVS ADD AUTHORIZER VARCHAR2(128) NULL;
DROP INDEX GLOBALPRIVILEGEINDEX;
CREATE UNIQUE INDEX GLOBALPRIVILEGEINDEX ON GLOBAL_PRIVS (AUTHORIZER,PRINCIPAL_NAME,PRINCIPAL_TYPE,USER_PRIV,GRANTOR,GRANTOR_TYPE);

ALTER TABLE DB_PRIVS ADD AUTHORIZER VARCHAR2(128) NULL;
DROP INDEX DBPRIVILEGEINDEX;
CREATE UNIQUE INDEX DBPRIVILEGEINDEX ON DB_PRIVS (AUTHORIZER,DB_ID,PRINCIPAL_NAME,PRINCIPAL_TYPE,DB_PRIV,GRANTOR,GRANTOR_TYPE);

ALTER TABLE TBL_PRIVS ADD AUTHORIZER VARCHAR2(128) NULL;
DROP INDEX TABLEPRIVILEGEINDEX;
CREATE INDEX TABLEPRIVILEGEINDEX ON TBL_PRIVS (AUTHORIZER,TBL_ID,PRINCIPAL_NAME,PRINCIPAL_TYPE,TBL_PRIV,GRANTOR,GRANTOR_TYPE);

ALTER TABLE PART_PRIVS ADD AUTHORIZER VARCHAR2(128) NULL;
DROP INDEX PARTPRIVILEGEINDEX;
CREATE INDEX PARTPRIVILEGEINDEX ON PART_PRIVS (AUTHORIZER,PART_ID,PRINCIPAL_NAME,PRINCIPAL_TYPE,PART_PRIV,GRANTOR,GRANTOR_TYPE);

ALTER TABLE TBL_COL_PRIVS ADD AUTHORIZER VARCHAR2(128) NULL;
DROP INDEX TABLECOLUMNPRIVILEGEINDEX;
CREATE INDEX TABLECOLUMNPRIVILEGEINDEX ON TBL_COL_PRIVS (AUTHORIZER,TBL_ID,"COLUMN_NAME",PRINCIPAL_NAME,PRINCIPAL_TYPE,TBL_COL_PRIV,GRANTOR,GRANTOR_TYPE);

ALTER TABLE PART_COL_PRIVS ADD AUTHORIZER VARCHAR2(128) NULL;
DROP INDEX PARTITIONCOLUMNPRIVILEGEINDEX;
CREATE INDEX PARTITIONCOLUMNPRIVILEGEINDEX ON PART_COL_PRIVS (AUTHORIZER,PART_ID,"COLUMN_NAME",PRINCIPAL_NAME,PRINCIPAL_TYPE,PART_COL_PRIV,GRANTOR,GRANTOR_TYPE);

-- HIVE-19340
ALTER TABLE TXNS ADD TXN_TYPE number(10) NULL;

CREATE INDEX TAB_COL_STATS_IDX ON TAB_COL_STATS (CAT_NAME, DB_NAME, TABLE_NAME, COLUMN_NAME);

--HIVE-19323
-- Update TXN_COMPONENTS
ALTER TABLE TXN_COMPONENTS ADD TC_CATALOG VARCHAR2(256);
UPDATE TXN_COMPONENTS 
  SET TC_CATALOG = 'hive';
ALTER TABLE TXN_COMPONENTS MODIFY TC_CATALOG NOT NULL;

-- Update COMPLETED_TXN_COMPONENTS
ALTER TABLE COMPLETED_TXN_COMPONENTS ADD CTC_CATALOG VARCHAR2(256);
UPDATE COMPLETED_TXN_COMPONENTS 
  SET CTC_CATALOG = 'hive';
ALTER TABLE COMPLETED_TXN_COMPONENTS MODIFY CTC_CATALOG NOT NULL;

DROP INDEX COMPLETED_TXN_COMPONENTS_INDEX;
CREATE INDEX COMPLETED_TXN_COMPONENTS_INDEX ON COMPLETED_TXN_COMPONENTS (CTC_CATALOG, CTC_DATABASE, CTC_TABLE, CTC_PARTITION);

-- Update HIVE_LOCKS
ALTER TABLE HIVE_LOCKS ADD HL_CATALOG VARCHAR2(256);
UPDATE HIVE_LOCKS 
  SET HL_CATALOG = 'hive';
ALTER TABLE HIVE_LOCKS MODIFY HL_CATALOG NOT NULL;

-- Update COMPACTION_QUEUE
ALTER TABLE COMPACTION_QUEUE ADD CQ_CATALOG VARCHAR2(256);
UPDATE COMPACTION_QUEUE 
  SET CQ_CATALOG = 'hive';
ALTER TABLE COMPACTION_QUEUE MODIFY CQ_CATALOG NOT NULL;

-- Update COMPLETED_COMPACTIONS
ALTER TABLE COMPLETED_COMPACTIONS ADD CC_CATALOG VARCHAR2(256);
UPDATE COMPLETED_COMPACTIONS 
  SET CC_CATALOG = 'hive';
ALTER TABLE COMPLETED_COMPACTIONS MODIFY CC_CATALOG NOT NULL;

-- Update WRITE_SET
ALTER TABLE WRITE_SET ADD WS_CATALOG VARCHAR2(256);
UPDATE WRITE_SET 
  SET WS_CATALOG = 'hive';
ALTER TABLE WRITE_SET MODIFY WS_CATALOG NOT NULL;

-- Update TXN_TO_WRITE_ID
ALTER TABLE TXN_TO_WRITE_ID ADD T2W_CATALOG VARCHAR2(256);
UPDATE TXN_TO_WRITE_ID 
  SET T2W_CATALOG = 'hive';
ALTER TABLE TXN_TO_WRITE_ID MODIFY T2W_CATALOG NOT NULL;

DROP INDEX TBL_TO_TXN_ID_IDX;
DROP INDEX TBL_TO_WRITE_ID_IDX;
CREATE UNIQUE INDEX TBL_TO_TXN_ID_IDX ON TXN_TO_WRITE_ID (T2W_CATALOG, T2W_DATABASE, T2W_TABLE, T2W_TXNID);
CREATE UNIQUE INDEX TBL_TO_WRITE_ID_IDX ON TXN_TO_WRITE_ID (T2W_CATALOG, T2W_DATABASE, T2W_TABLE, T2W_WRITEID);

-- Update NEXT_WRITE_ID
ALTER TABLE NEXT_WRITE_ID ADD NWI_CATALOG VARCHAR2(256);
UPDATE NEXT_WRITE_ID 
  SET NWI_CATALOG = 'hive';
ALTER TABLE NEXT_WRITE_ID MODIFY NWI_CATALOG NOT NULL;

DROP INDEX NEXT_WRITE_ID_IDX;
CREATE UNIQUE INDEX NEXT_WRITE_ID_IDX ON NEXT_WRITE_ID (NWI_CATALOG, NWI_DATABASE, NWI_TABLE);

-- These lines need to be last.  Insert any changes above.
UPDATE VERSION SET SCHEMA_VERSION='3.1.0', VERSION_COMMENT='Hive release version 3.1.0' where VER_ID=1;
SELECT 'Finished upgrading MetaStore schema from 3.0.0 to 3.1.0' AS Status from dual;
