CREATE DATABASE _REPLACE_WITH_DB_;
use _REPLACE_WITH_DB_;
CREATE LOGIN _REPLACE_WITH_USER_ WITH PASSWORD='_REPLACE_WITH_PASSWD_';
CREATE USER _REPLACE_WITH_USER_ FOR LOGIN _REPLACE_WITH_USER_;
ALTER ROLE db_owner ADD MEMBER _REPLACE_WITH_USER_;
