--
-- Licensed to the Apache Software Foundation (ASF) under one or more
-- contributor license agreements.  See the NOTICE file distributed with
-- this work for additional information regarding copyright ownership.
-- The ASF licenses this file to you under the Apache License, Version 2.0
-- (the "License"); you may not use this file except in compliance with
-- the License.  You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--
-- Rebuilds all HMS standalone indexes on MSSQL (DROP IF EXISTS + CREATE).
-- Update this file whenever a new upgrade script adds an index.

DROP INDEX IF EXISTS BUCKETING_COLS_N49 ON BUCKETING_COLS;
CREATE INDEX BUCKETING_COLS_N49 ON BUCKETING_COLS (SD_ID);

DROP INDEX IF EXISTS COLUMNS_V2_N49 ON COLUMNS_V2;
CREATE INDEX COLUMNS_V2_N49 ON COLUMNS_V2 (CD_ID);

DROP INDEX IF EXISTS COMPLETED_COMPACTIONS_RES ON COMPLETED_COMPACTIONS;
CREATE INDEX COMPLETED_COMPACTIONS_RES ON COMPLETED_COMPACTIONS (CC_DATABASE,CC_TABLE,CC_PARTITION);

DROP INDEX IF EXISTS COMPLETED_TXN_COMPONENTS_IDX ON COMPLETED_TXN_COMPONENTS;
CREATE INDEX COMPLETED_TXN_COMPONENTS_IDX ON COMPLETED_TXN_COMPONENTS (CTC_DATABASE, CTC_TABLE, CTC_PARTITION);

DROP INDEX IF EXISTS CONSTRAINTS_CONSTRAINT_TYPE_INDEX ON KEY_CONSTRAINTS;
CREATE INDEX CONSTRAINTS_CONSTRAINT_TYPE_INDEX ON KEY_CONSTRAINTS(CONSTRAINT_TYPE);

DROP INDEX IF EXISTS CONSTRAINTS_PARENT_TBL_ID__INDEX ON KEY_CONSTRAINTS;
CREATE INDEX CONSTRAINTS_PARENT_TBL_ID__INDEX ON KEY_CONSTRAINTS(PARENT_TBL_ID);

DROP INDEX IF EXISTS DATABASE_PARAMS_N49 ON DATABASE_PARAMS;
CREATE INDEX DATABASE_PARAMS_N49 ON DATABASE_PARAMS (DB_ID);

DROP INDEX IF EXISTS DBPRIVILEGEINDEX ON DB_PRIVS;
CREATE UNIQUE INDEX DBPRIVILEGEINDEX ON DB_PRIVS (AUTHORIZER,DB_ID,PRINCIPAL_NAME,PRINCIPAL_TYPE,DB_PRIV,GRANTOR,GRANTOR_TYPE);

DROP INDEX IF EXISTS DB_PRIVS_N49 ON DB_PRIVS;
CREATE INDEX DB_PRIVS_N49 ON DB_PRIVS (DB_ID);

DROP INDEX IF EXISTS DCPRIVILEGEINDEX ON DC_PRIVS;
CREATE UNIQUE INDEX DCPRIVILEGEINDEX ON DC_PRIVS (AUTHORIZER,NAME,PRINCIPAL_NAME,PRINCIPAL_TYPE,DC_PRIV,GRANTOR,GRANTOR_TYPE);

DROP INDEX IF EXISTS DC_PRIVS_N49 ON DC_PRIVS;
CREATE INDEX DC_PRIVS_N49 ON DC_PRIVS (NAME);

DROP INDEX IF EXISTS DUMP_IDX ON REPLICATION_METRICS;
CREATE INDEX "DUMP_IDX" ON "REPLICATION_METRICS" ("RM_DUMP_EXECUTION_ID");

DROP INDEX IF EXISTS FUNCS_N49 ON FUNCS;
CREATE INDEX FUNCS_N49 ON FUNCS (DB_ID);

DROP INDEX IF EXISTS FUNC_RU_N49 ON FUNC_RU;
CREATE INDEX FUNC_RU_N49 ON FUNC_RU (FUNC_ID);

DROP INDEX IF EXISTS GLOBALPRIVILEGEINDEX ON GLOBAL_PRIVS;
CREATE UNIQUE INDEX GLOBALPRIVILEGEINDEX ON GLOBAL_PRIVS (AUTHORIZER,PRINCIPAL_NAME,PRINCIPAL_TYPE,USER_PRIV,GRANTOR,GRANTOR_TYPE);

DROP INDEX IF EXISTS IDX_RUNTIME_STATS_CREATE_TIME ON RUNTIME_STATS;
CREATE INDEX IDX_RUNTIME_STATS_CREATE_TIME ON RUNTIME_STATS(CREATE_TIME);

DROP INDEX IF EXISTS IDX_SCHEDULED_EX_LAST_UPDATE ON SCHEDULED_EXECUTIONS;
CREATE INDEX IDX_SCHEDULED_EX_LAST_UPDATE ON "SCHEDULED_EXECUTIONS" ("LAST_UPDATE_TIME");

DROP INDEX IF EXISTS IDX_SCHEDULED_EX_SQ_ID ON SCHEDULED_EXECUTIONS;
CREATE INDEX IDX_SCHEDULED_EX_SQ_ID ON "SCHEDULED_EXECUTIONS" ("SCHEDULED_QUERY_ID");

DROP INDEX IF EXISTS MIN_HISTORY_LEVEL_IDX ON MIN_HISTORY_LEVEL;
CREATE INDEX MIN_HISTORY_LEVEL_IDX ON MIN_HISTORY_LEVEL (MHL_MIN_OPEN_TXNID);

DROP INDEX IF EXISTS MIN_HISTORY_WRITE_ID_IDX ON MIN_HISTORY_WRITE_ID;
CREATE INDEX MIN_HISTORY_WRITE_ID_IDX ON MIN_HISTORY_WRITE_ID (MH_DATABASE, MH_TABLE, MH_WRITEID);

DROP INDEX IF EXISTS MV_UNIQUE_TABLE ON MV_CREATION_METADATA;
CREATE INDEX MV_UNIQUE_TABLE ON MV_CREATION_METADATA (TBL_NAME,DB_NAME);

DROP INDEX IF EXISTS NEXT_WRITE_ID_IDX ON NEXT_WRITE_ID;
CREATE UNIQUE INDEX NEXT_WRITE_ID_IDX ON NEXT_WRITE_ID (NWI_DATABASE, NWI_TABLE);

DROP INDEX IF EXISTS NOTIFICATION_LOG_EVENT_ID ON NOTIFICATION_LOG;
CREATE UNIQUE INDEX NOTIFICATION_LOG_EVENT_ID ON NOTIFICATION_LOG (EVENT_ID);

DROP INDEX IF EXISTS PARTITIONCOLUMNPRIVILEGEINDEX ON PART_COL_PRIVS;
CREATE INDEX PARTITIONCOLUMNPRIVILEGEINDEX ON PART_COL_PRIVS (AUTHORIZER,PART_ID,"COLUMN_NAME",PRINCIPAL_NAME,PRINCIPAL_TYPE,PART_COL_PRIV,GRANTOR,GRANTOR_TYPE);

DROP INDEX IF EXISTS PARTITIONEVENTINDEX ON PARTITION_EVENTS;
CREATE INDEX PARTITIONEVENTINDEX ON PARTITION_EVENTS (PARTITION_NAME);

DROP INDEX IF EXISTS PARTITIONS_N49 ON PARTITIONS;
CREATE INDEX PARTITIONS_N49 ON PARTITIONS (SD_ID);

DROP INDEX IF EXISTS PARTITION_KEYS_N49 ON PARTITION_KEYS;
CREATE INDEX PARTITION_KEYS_N49 ON PARTITION_KEYS (TBL_ID);

DROP INDEX IF EXISTS PARTITION_KEY_VALS_N49 ON PARTITION_KEY_VALS;
CREATE INDEX PARTITION_KEY_VALS_N49 ON PARTITION_KEY_VALS (PART_ID);

DROP INDEX IF EXISTS PARTITION_PARAMS_N49 ON PARTITION_PARAMS;
CREATE INDEX PARTITION_PARAMS_N49 ON PARTITION_PARAMS (PART_ID);

DROP INDEX IF EXISTS PARTPRIVILEGEINDEX ON PART_PRIVS;
CREATE INDEX PARTPRIVILEGEINDEX ON PART_PRIVS (AUTHORIZER,PART_ID,PRINCIPAL_NAME,PRINCIPAL_TYPE,PART_PRIV,GRANTOR,GRANTOR_TYPE);

DROP INDEX IF EXISTS PART_COL_PRIVS_N49 ON PART_COL_PRIVS;
CREATE INDEX PART_COL_PRIVS_N49 ON PART_COL_PRIVS (PART_ID);

DROP INDEX IF EXISTS PART_PRIVS_N49 ON PART_PRIVS;
CREATE INDEX PART_PRIVS_N49 ON PART_PRIVS (PART_ID);

DROP INDEX IF EXISTS PART_TABLE_PK ON SEQUENCE_TABLE;
CREATE UNIQUE INDEX PART_TABLE_PK ON SEQUENCE_TABLE (SEQUENCE_NAME);

DROP INDEX IF EXISTS PCS_STATS_IDX ON PART_COL_STATS;
CREATE INDEX PCS_STATS_IDX ON PART_COL_STATS (PART_ID,COLUMN_NAME);

DROP INDEX IF EXISTS POLICY_IDX ON REPLICATION_METRICS;
CREATE INDEX "POLICY_IDX" ON "REPLICATION_METRICS" ("RM_POLICY");

DROP INDEX IF EXISTS ROLEENTITYINDEX ON ROLES;
CREATE UNIQUE INDEX ROLEENTITYINDEX ON ROLES (ROLE_NAME);

DROP INDEX IF EXISTS ROLE_MAP_N49 ON ROLE_MAP;
CREATE INDEX ROLE_MAP_N49 ON ROLE_MAP (ROLE_ID);

DROP INDEX IF EXISTS SDS_N49 ON SDS;
CREATE INDEX SDS_N49 ON SDS (SERDE_ID);

DROP INDEX IF EXISTS SDS_N50 ON SDS;
CREATE INDEX SDS_N50 ON SDS (CD_ID);

DROP INDEX IF EXISTS SD_PARAMS_N49 ON SD_PARAMS;
CREATE INDEX SD_PARAMS_N49 ON SD_PARAMS (SD_ID);

DROP INDEX IF EXISTS SERDE_PARAMS_N49 ON SERDE_PARAMS;
CREATE INDEX SERDE_PARAMS_N49 ON SERDE_PARAMS (SERDE_ID);

DROP INDEX IF EXISTS SKEWED_COL_NAMES_N49 ON SKEWED_COL_NAMES;
CREATE INDEX SKEWED_COL_NAMES_N49 ON SKEWED_COL_NAMES (SD_ID);

DROP INDEX IF EXISTS SKEWED_COL_VALUE_LOC_MAP_N49 ON SKEWED_COL_VALUE_LOC_MAP;
CREATE INDEX SKEWED_COL_VALUE_LOC_MAP_N49 ON SKEWED_COL_VALUE_LOC_MAP (SD_ID);

DROP INDEX IF EXISTS SKEWED_COL_VALUE_LOC_MAP_N50 ON SKEWED_COL_VALUE_LOC_MAP;
CREATE INDEX SKEWED_COL_VALUE_LOC_MAP_N50 ON SKEWED_COL_VALUE_LOC_MAP (STRING_LIST_ID_KID);

DROP INDEX IF EXISTS SKEWED_STRING_LIST_VALUES_N49 ON SKEWED_STRING_LIST_VALUES;
CREATE INDEX SKEWED_STRING_LIST_VALUES_N49 ON SKEWED_STRING_LIST_VALUES (STRING_LIST_ID);

DROP INDEX IF EXISTS SKEWED_VALUES_N49 ON SKEWED_VALUES;
CREATE INDEX SKEWED_VALUES_N49 ON SKEWED_VALUES (STRING_LIST_ID_EID);

DROP INDEX IF EXISTS SKEWED_VALUES_N50 ON SKEWED_VALUES;
CREATE INDEX SKEWED_VALUES_N50 ON SKEWED_VALUES (SD_ID_OID);

DROP INDEX IF EXISTS SORT_COLS_N49 ON SORT_COLS;
CREATE INDEX SORT_COLS_N49 ON SORT_COLS (SD_ID);

DROP INDEX IF EXISTS TABLECOLUMNPRIVILEGEINDEX ON TBL_COL_PRIVS;
CREATE INDEX TABLECOLUMNPRIVILEGEINDEX ON TBL_COL_PRIVS (AUTHORIZER,TBL_ID,"COLUMN_NAME",PRINCIPAL_NAME,PRINCIPAL_TYPE,TBL_COL_PRIV,GRANTOR,GRANTOR_TYPE);

DROP INDEX IF EXISTS TABLEPRIVILEGEINDEX ON TBL_PRIVS;
CREATE INDEX TABLEPRIVILEGEINDEX ON TBL_PRIVS (AUTHORIZER,TBL_ID,PRINCIPAL_NAME,PRINCIPAL_TYPE,TBL_PRIV,GRANTOR,GRANTOR_TYPE);

DROP INDEX IF EXISTS TABLE_PARAMS_N49 ON TABLE_PARAMS;
CREATE INDEX TABLE_PARAMS_N49 ON TABLE_PARAMS (TBL_ID);

DROP INDEX IF EXISTS TAB_COL_STATS_IDX ON TAB_COL_STATS;
CREATE INDEX TAB_COL_STATS_IDX ON TAB_COL_STATS (TBL_ID, COLUMN_NAME);

DROP INDEX IF EXISTS TBLS_N50 ON TBLS;
CREATE INDEX TBLS_N50 ON TBLS (SD_ID);

DROP INDEX IF EXISTS TBL_COL_PRIVS_N49 ON TBL_COL_PRIVS;
CREATE INDEX TBL_COL_PRIVS_N49 ON TBL_COL_PRIVS (TBL_ID);

DROP INDEX IF EXISTS TBL_PRIVS_N49 ON TBL_PRIVS;
CREATE INDEX TBL_PRIVS_N49 ON TBL_PRIVS (TBL_ID);

DROP INDEX IF EXISTS TBL_TO_TXN_ID_IDX ON TXN_TO_WRITE_ID;
CREATE UNIQUE INDEX TBL_TO_TXN_ID_IDX ON TXN_TO_WRITE_ID (T2W_DATABASE, T2W_TABLE, T2W_TXNID);

DROP INDEX IF EXISTS TBL_TO_WRITE_ID_IDX ON TXN_TO_WRITE_ID;
CREATE UNIQUE INDEX TBL_TO_WRITE_ID_IDX ON TXN_TO_WRITE_ID (T2W_DATABASE, T2W_TABLE, T2W_WRITEID);

DROP INDEX IF EXISTS TC_TXNID_INDEX ON TXN_COMPONENTS;
CREATE INDEX TC_TXNID_INDEX ON TXN_COMPONENTS (TC_TXNID);

DROP INDEX IF EXISTS TYPE_FIELDS_N49 ON TYPE_FIELDS;
CREATE INDEX TYPE_FIELDS_N49 ON TYPE_FIELDS (TYPE_NAME);

DROP INDEX IF EXISTS UNIQUEDATABASE ON DBS;
CREATE UNIQUE INDEX UNIQUEDATABASE ON DBS ("NAME", "CTLG_NAME");

DROP INDEX IF EXISTS UNIQUEFUNCTION ON FUNCS;
CREATE UNIQUE INDEX UNIQUEFUNCTION ON FUNCS (FUNC_NAME,DB_ID);

DROP INDEX IF EXISTS UNIQUEPARTITION ON PARTITIONS;
CREATE UNIQUE INDEX UNIQUEPARTITION ON PARTITIONS (TBL_ID,PART_NAME);

DROP INDEX IF EXISTS UNIQUEPKG ON PACKAGES;
CREATE UNIQUE INDEX "UNIQUEPKG" ON "PACKAGES" ("NAME", "DB_ID");

DROP INDEX IF EXISTS UNIQUESTOREDPROC ON STORED_PROCS;
CREATE UNIQUE INDEX "UNIQUESTOREDPROC" ON "STORED_PROCS" ("NAME", "DB_ID");

DROP INDEX IF EXISTS UNIQUETABLE ON TBLS;
CREATE UNIQUE INDEX UNIQUETABLE ON TBLS (DB_ID,TBL_NAME);

DROP INDEX IF EXISTS UNIQUETYPE ON TYPES;
CREATE UNIQUE INDEX UNIQUETYPE ON TYPES (TYPE_NAME);

DROP INDEX IF EXISTS UNIQUE_CTLG ON CTLGS;
CREATE UNIQUE INDEX UNIQUE_CTLG ON CTLGS ("NAME");

DROP INDEX IF EXISTS UNIQUE_WM_MAPPING ON WM_MAPPING;
CREATE UNIQUE INDEX UNIQUE_WM_MAPPING ON WM_MAPPING (RP_ID, ENTITY_TYPE, ENTITY_NAME);

DROP INDEX IF EXISTS UNIQUE_WM_POOL ON WM_POOL;
CREATE UNIQUE INDEX UNIQUE_WM_POOL ON WM_POOL (RP_ID, PATH);

DROP INDEX IF EXISTS UNIQUE_WM_RESOURCEPLAN ON WM_RESOURCEPLAN;
CREATE UNIQUE INDEX UNIQUE_WM_RESOURCEPLAN ON WM_RESOURCEPLAN ("NS", "NAME");

DROP INDEX IF EXISTS UNIQUE_WM_TRIGGER ON WM_TRIGGER;
CREATE UNIQUE INDEX UNIQUE_WM_TRIGGER ON WM_TRIGGER (RP_ID, "NAME");

DROP INDEX IF EXISTS USERROLEMAPINDEX ON ROLE_MAP;
CREATE UNIQUE INDEX USERROLEMAPINDEX ON ROLE_MAP (PRINCIPAL_NAME,ROLE_ID,GRANTOR,GRANTOR_TYPE);

