SELECT 'Upgrading MetaStore schema from  4.0.0 to 4.1.0' AS MESSAGE;

-- HIVE-27725
DROP INDEX TAB_COL_STATS_IDX ON TAB_COL_STATS;
CREATE INDEX TAB_COL_STATS_IDX ON TAB_COL_STATS (TBL_ID, COLUMN_NAME);
DROP INDEX TAB_COL_STATS_N49 ON TAB_COL_STATS;
ALTER TABLE TAB_COL_STATS DROP COLUMN CAT_NAME, DB_NAME, TABLE_NAME;

DROP INDEX PCS_STATS_IDX ON PART_COL_STATS;
CREATE INDEX PCS_STATS_IDX ON PART_COL_STATS (PART_ID,COLUMN_NAME);
DROP INDEX PART_COL_STATS_N49 on PART_COL_STATS;
ALTER TABLE PART_COL_STATS DROP COLUMN CAT_NAME, DB_NAME, TABLE_NAME, PARTITION_NAME;

-- HIVE-28292
DROP INDEX UNIQUETABLE ON TBLS;
CREATE UNIQUE INDEX UNIQUETABLE ON TBLS (DB_ID,TBL_NAME);
DROP INDEX TBLS_N49 ON TBLS;

-- HIVE-17306
ALTER TABLE COMPLETED_TXN_COMPONENTS ADD INV_ID BIGINT IDENTITY(1,1) PRIMARY KEY;
ALTER TABLE NEXT_COMPACTION_QUEUE_ID ADD CONSTRAINT NEXT_COMPACTION_QUEUE_ID_PK PRIMARY KEY (NCQ_NEXT);
ALTER TABLE NEXT_LOCK_ID ADD CONSTRAINT NEXT_LOCK_ID_PK PRIMARY KEY (NL_NEXT);
ALTER TABLE TXN_LOCK_TBL ADD CONSTRAINT TXN_LOCK_TBL_PK PRIMARY KEY (TXN_LOCK);
ALTER TABLE NEXT_WRITE_ID ADD CONSTRAINT NEXT_WRITE_ID_PK PRIMARY KEY (NWI_TABLE, NWI_DATABASE);
ALTER TABLE TXN_COMPONENTS ADD INV_ID BIGINT IDENTITY(1,1) PRIMARY KEY;
ALTER TABLE TXN_TO_WRITE_ID ADD CONSTRAINT TXN_TO_WRITE_ID_PK PRIMARY KEY (T2W_TXNID, T2W_DATABASE, T2W_TABLE);
ALTER TABLE WRITE_SET ADD INV_ID BIGINT IDENTITY(1,1) PRIMARY KEY;
ALTER TABLE COMPACTION_METRICS_CACHE ADD INV_ID BIGINT IDENTITY(1,1) PRIMARY KEY;
ALTER TABLE MIN_HISTORY_WRITE_ID ADD CONSTRAINT MIN_HISTORY_WRITE_ID_PK PRIMARY KEY (MH_TXNID, MH_DATABASE, MH_TABLE, MH_WRITEID);

-- These lines need to be last.  Insert any changes above.
UPDATE VERSION SET SCHEMA_VERSION='4.1.0', VERSION_COMMENT='Hive release version 4.1.0' where VER_ID=1;
SELECT 'Finished upgrading MetaStore schema from 4.0.0 to 4.1.0' AS MESSAGE;
