SELECT 'Upgrading MetaStore schema from  4.2.0 to 4.3.0' AS MESSAGE;

ALTER TABLE HIVE_LOCKS ADD HL_CATALOG nvarchar(128) NOT NULL DEFAULT 'hive';
ALTER TABLE MATERIALIZATION_REBUILD_LOCKS ADD MRL_CAT_NAME nvarchar(128) NOT NULL DEFAULT 'hive';

-- Add surrogate primary keys for HA database replication. Adding IDENTITY columns
-- and clustered PKs via ALTER TABLE takes schema modification locks and rebuilds
-- large tables. Rebuild each populated table via a TMP_* copy/swap instead.
-- Counter tables contain a single row and keep the two-step ALTER form. Plan a
-- maintenance window for busy metastores; duration scales with row counts.

CREATE TABLE TMP_TXN_COMPONENTS(
  TC_ID bigint NOT NULL IDENTITY(1,1),
  TC_TXNID bigint NOT NULL,
  TC_DATABASE nvarchar(128) NOT NULL,
  TC_TABLE nvarchar(256) NULL,
  TC_PARTITION nvarchar(767) NULL,
  TC_OPERATION_TYPE char(1) NOT NULL,
  TC_WRITEID bigint,
  PRIMARY KEY CLUSTERED (TC_ID ASC)
);
INSERT INTO TMP_TXN_COMPONENTS (TC_TXNID, TC_DATABASE, TC_TABLE, TC_PARTITION, TC_OPERATION_TYPE, TC_WRITEID)
  SELECT TC_TXNID, TC_DATABASE, TC_TABLE, TC_PARTITION, TC_OPERATION_TYPE, TC_WRITEID FROM TXN_COMPONENTS;
DROP TABLE TXN_COMPONENTS;
EXEC sp_rename 'TMP_TXN_COMPONENTS', 'TXN_COMPONENTS';
ALTER TABLE TXN_COMPONENTS WITH CHECK ADD FOREIGN KEY(TC_TXNID) REFERENCES TXNS (TXN_ID);
CREATE INDEX TC_TXNID_INDEX ON TXN_COMPONENTS (TC_TXNID);

CREATE TABLE TMP_COMPLETED_TXN_COMPONENTS(
  CTC_ID bigint NOT NULL IDENTITY(1,1),
  CTC_TXNID bigint NOT NULL,
  CTC_DATABASE nvarchar(128) NOT NULL,
  CTC_TABLE nvarchar(256) NULL,
  CTC_PARTITION nvarchar(767) NULL,
  CTC_TIMESTAMP datetime2 DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CTC_WRITEID bigint,
  CTC_UPDATE_DELETE char(1) NOT NULL,
  PRIMARY KEY CLUSTERED (CTC_ID ASC)
);
INSERT INTO TMP_COMPLETED_TXN_COMPONENTS (CTC_TXNID, CTC_DATABASE, CTC_TABLE, CTC_PARTITION, CTC_TIMESTAMP, CTC_WRITEID, CTC_UPDATE_DELETE)
  SELECT CTC_TXNID, CTC_DATABASE, CTC_TABLE, CTC_PARTITION, CTC_TIMESTAMP, CTC_WRITEID, CTC_UPDATE_DELETE FROM COMPLETED_TXN_COMPONENTS;
DROP TABLE COMPLETED_TXN_COMPONENTS;
EXEC sp_rename 'TMP_COMPLETED_TXN_COMPONENTS', 'COMPLETED_TXN_COMPONENTS';
CREATE INDEX COMPLETED_TXN_COMPONENTS_IDX ON COMPLETED_TXN_COMPONENTS (CTC_DATABASE, CTC_TABLE, CTC_PARTITION);

CREATE TABLE TMP_COMPACTION_METRICS_CACHE (
  CMC_ID bigint NOT NULL IDENTITY(1,1),
  CMC_DATABASE nvarchar(128) NOT NULL,
  CMC_TABLE nvarchar(256) NOT NULL,
  CMC_PARTITION nvarchar(767) NULL,
  CMC_METRIC_TYPE nvarchar(128) NOT NULL,
  CMC_METRIC_VALUE int NOT NULL,
  CMC_VERSION int NOT NULL,
  PRIMARY KEY CLUSTERED (CMC_ID ASC)
);
INSERT INTO TMP_COMPACTION_METRICS_CACHE (CMC_DATABASE, CMC_TABLE, CMC_PARTITION, CMC_METRIC_TYPE, CMC_METRIC_VALUE, CMC_VERSION)
  SELECT CMC_DATABASE, CMC_TABLE, CMC_PARTITION, CMC_METRIC_TYPE, CMC_METRIC_VALUE, CMC_VERSION FROM COMPACTION_METRICS_CACHE;
DROP TABLE COMPACTION_METRICS_CACHE;
EXEC sp_rename 'TMP_COMPACTION_METRICS_CACHE', 'COMPACTION_METRICS_CACHE';

CREATE TABLE TMP_WRITE_SET (
  WS_ID bigint NOT NULL IDENTITY(1,1),
  WS_DATABASE nvarchar(128) NOT NULL,
  WS_TABLE nvarchar(256) NOT NULL,
  WS_PARTITION nvarchar(767),
  WS_TXNID bigint NOT NULL,
  WS_COMMIT_ID bigint NOT NULL,
  WS_OPERATION_TYPE char(1) NOT NULL,
  PRIMARY KEY CLUSTERED (WS_ID ASC)
);
INSERT INTO TMP_WRITE_SET (WS_DATABASE, WS_TABLE, WS_PARTITION, WS_TXNID, WS_COMMIT_ID, WS_OPERATION_TYPE)
  SELECT WS_DATABASE, WS_TABLE, WS_PARTITION, WS_TXNID, WS_COMMIT_ID, WS_OPERATION_TYPE FROM WRITE_SET;
DROP TABLE WRITE_SET;
EXEC sp_rename 'TMP_WRITE_SET', 'WRITE_SET';

DROP INDEX TBL_TO_TXN_ID_IDX ON TXN_TO_WRITE_ID;
ALTER TABLE TXN_TO_WRITE_ID ADD CONSTRAINT TXN_TO_WRITE_ID_PK PRIMARY KEY CLUSTERED (T2W_DATABASE, T2W_TABLE, T2W_TXNID);

DROP INDEX NEXT_WRITE_ID_IDX ON NEXT_WRITE_ID;
ALTER TABLE NEXT_WRITE_ID ADD CONSTRAINT NEXT_WRITE_ID_PK PRIMARY KEY CLUSTERED (NWI_DATABASE, NWI_TABLE);

CREATE TABLE TMP_MIN_HISTORY_WRITE_ID (
  MH_ID bigint NOT NULL IDENTITY(1,1),
  MH_TXNID bigint NOT NULL,
  MH_DATABASE nvarchar(128) NOT NULL,
  MH_TABLE nvarchar(256) NOT NULL,
  MH_WRITEID bigint NOT NULL,
  PRIMARY KEY CLUSTERED (MH_ID ASC)
);
INSERT INTO TMP_MIN_HISTORY_WRITE_ID (MH_TXNID, MH_DATABASE, MH_TABLE, MH_WRITEID)
  SELECT MH_TXNID, MH_DATABASE, MH_TABLE, MH_WRITEID FROM MIN_HISTORY_WRITE_ID;
DROP TABLE MIN_HISTORY_WRITE_ID;
EXEC sp_rename 'TMP_MIN_HISTORY_WRITE_ID', 'MIN_HISTORY_WRITE_ID';
CREATE INDEX MIN_HISTORY_WRITE_ID_IDX ON MIN_HISTORY_WRITE_ID (MH_DATABASE, MH_TABLE, MH_WRITEID);

ALTER TABLE TXN_LOCK_TBL ADD TLT_ID bigint IDENTITY(1,1) NOT NULL;
ALTER TABLE TXN_LOCK_TBL ADD CONSTRAINT TXN_LOCK_TBL_PK PRIMARY KEY CLUSTERED (TLT_ID);

ALTER TABLE NEXT_LOCK_ID ADD NL_ID bigint IDENTITY(1,1) NOT NULL;
ALTER TABLE NEXT_LOCK_ID ADD CONSTRAINT NEXT_LOCK_ID_PK PRIMARY KEY CLUSTERED (NL_ID);

ALTER TABLE NEXT_COMPACTION_QUEUE_ID ADD NCQI_ID bigint IDENTITY(1,1) NOT NULL;
ALTER TABLE NEXT_COMPACTION_QUEUE_ID ADD CONSTRAINT NEXT_COMPACTION_QUEUE_ID_PK PRIMARY KEY CLUSTERED (NCQI_ID);

-- These lines need to be last.  Insert any changes above.
UPDATE VERSION SET SCHEMA_VERSION='4.3.0', VERSION_COMMENT='Hive release version 4.3.0' where VER_ID=1;
SELECT 'Finished upgrading MetaStore schema from 4.2.0 to 4.3.0' AS MESSAGE;
