SELECT 'Upgrading MetaStore schema from  4.2.0 to 4.3.0' AS MESSAGE;

DROP INDEX COMPLETED_TXN_COMPONENTS_IDX ON COMPLETED_TXN_COMPONENTS;
DROP INDEX COMPLETED_COMPACTIONS_RES ON COMPLETED_COMPACTIONS;
DROP INDEX TBL_TO_TXN_ID_IDX ON TXN_TO_WRITE_ID;
DROP INDEX TBL_TO_WRITE_ID_IDX ON TXN_TO_WRITE_ID;
DROP INDEX NEXT_WRITE_ID_IDX ON NEXT_WRITE_ID;

ALTER TABLE HIVE_LOCKS ADD HL_CATALOG nvarchar(128) NOT NULL DEFAULT 'hive';
ALTER TABLE MATERIALIZATION_REBUILD_LOCKS ADD MRL_CAT_NAME nvarchar(128) NOT NULL DEFAULT 'hive';
ALTER TABLE TXN_COMPONENTS ADD TC_CATALOG nvarchar(128) NOT NULL DEFAULT 'hive';
ALTER TABLE COMPLETED_TXN_COMPONENTS ADD CTC_CATALOG nvarchar(128) NOT NULL DEFAULT 'hive';
ALTER TABLE COMPACTION_QUEUE ADD CQ_CATALOG nvarchar(128) NOT NULL DEFAULT 'hive';
ALTER TABLE COMPLETED_COMPACTIONS ADD CC_CATALOG nvarchar(128) NOT NULL DEFAULT 'hive';
ALTER TABLE COMPACTION_METRICS_CACHE ADD CMC_CATALOG nvarchar(128) NOT NULL DEFAULT 'hive';
ALTER TABLE WRITE_SET ADD WS_CATALOG nvarchar(128) NOT NULL DEFAULT 'hive';
ALTER TABLE TXN_TO_WRITE_ID ADD T2W_CATALOG nvarchar(128) NOT NULL DEFAULT 'hive';
ALTER TABLE NEXT_WRITE_ID ADD NWI_CATALOG nvarchar(128) NOT NULL DEFAULT 'hive';
ALTER TABLE MIN_HISTORY_WRITE_ID ADD MH_CATALOG nvarchar(128) NOT NULL DEFAULT 'hive';
ALTER TABLE TXN_WRITE_NOTIFICATION_LOG ADD WNL_CATALOG nvarchar(128) NOT NULL DEFAULT 'hive';
ALTER TABLE TXN_WRITE_NOTIFICATION_LOG DROP CONSTRAINT TXN_WRITE_NOTIFICATION_LOG_PK;

CREATE INDEX COMPLETED_TXN_COMPONENTS_IDX ON COMPLETED_TXN_COMPONENTS (CTC_CATALOG, CTC_DATABASE, CTC_TABLE, CTC_PARTITION);
CREATE INDEX COMPLETED_COMPACTIONS_RES ON COMPLETED_COMPACTIONS (CC_CATALOG, CC_DATABASE, CC_TABLE, CC_PARTITION);
CREATE UNIQUE INDEX TBL_TO_TXN_ID_IDX ON TXN_TO_WRITE_ID (T2W_CATALOG, T2W_DATABASE, T2W_TABLE, T2W_TXNID);
CREATE UNIQUE INDEX TBL_TO_WRITE_ID_IDX ON TXN_TO_WRITE_ID (T2W_CATALOG, T2W_DATABASE, T2W_TABLE, T2W_WRITEID);
CREATE UNIQUE INDEX NEXT_WRITE_ID_IDX ON NEXT_WRITE_ID (NWI_CATALOG, NWI_DATABASE, NWI_TABLE);
CREATE INDEX MIN_HISTORY_WRITE_ID_IDX ON MIN_HISTORY_WRITE_ID (MH_CATALOG, MH_DATABASE, MH_TABLE, MH_WRITEID);
ALTER TABLE TXN_WRITE_NOTIFICATION_LOG ADD CONSTRAINT TXN_WRITE_NOTIFICATION_LOG_PK PRIMARY KEY (WNL_TXNID, WNL_CATALOG, WNL_DATABASE, WNL_TABLE, WNL_PARTITION);

-- These lines need to be last.  Insert any changes above.
UPDATE VERSION SET SCHEMA_VERSION='4.3.0', VERSION_COMMENT='Hive release version 4.3.0' where VER_ID=1;
SELECT 'Finished upgrading MetaStore schema from 4.2.0 to 4.3.0' AS MESSAGE;
