#!/bin/bash

BASE="$1"

apdiff="git diff $BASE"

# +-- FIXME: p#1 
$apdiff -- `$apdiff --name-only |grep -v thrift/gen|
		grep -v '^standalone'|grep -v hive-schema-4.0.0.hive.sql`  > ../cdpd/p1
$apdiff -- `$apdiff --name-only |grep -v thrift/gen|
		grep common|grep ^standalone` |
	sed 's+schema-4.0.0+schema-3.1.0+' |
	sed 's+standalone-metastore/metastore-server/+standalone-metastore/+;s+standalone-metastore/metastore-common/+standalone-metastore/+' > ../cdpd/p2
# +-- FIXME: p#3
$apdiff -- `$apdiff --name-only |grep -v thrift/gen|
		grep -v hive-schema-4.0.0|grep server/|
		grep ^standalone` |
	sed 's+schema-4.0.0+schema-3.1.0+' |
	sed 's+standalone-metastore/metastore-server/+standalone-metastore/+;s+standalone-metastore/metastore-common/+standalone-metastore/+' > ../cdpd/p3

