#!/bin/bash
set -e

V="`xmlstarlet sel -t -m /_:project/_:version -v  . pom.xml`"
DATE="`date +%Y%m%d_%H%M%S`"
HASH="`git rev-parse --short HEAD`"
SUFFIX="nightly-$HASH-$DATE"

NEWV="${V/SNAPSHOT}$SUFFIX"
echo "$NEWV"

mvn versions:set -DnewVersion=$NEWV
