ALTER TABLE TXNS MODIFY (
  TXN_ID NUMBER(19),
  TXN_STARTED NUMBER(19),
  TXN_LAST_HEARTBEAT NUMBER(19)
);

ALTER TABLE TXN_COMPONENTS MODIFY (
  TC_TXNID NUMBER(19)
);

ALTER TABLE COMPLETED_TXN_COMPONENTS MODIFY (
  CTC_TXNID NUMBER(19)
);

ALTER TABLE NEXT_TXN_ID MODIFY (
  NTXN_NEXT NUMBER(19)
);

ALTER TABLE HIVE_LOCKS MODIFY (
  HL_LOCK_EXT_ID NUMBER(19),
  HL_LOCK_INT_ID NUMBER(19),
  HL_TXNID NUMBER(19),
  HL_LAST_HEARTBEAT NUMBER(19),
  HL_ACQUIRED_AT NUMBER(19)
);

ALTER TABLE NEXT_LOCK_ID MODIFY (
  NL_NEXT NUMBER(19)
);

ALTER TABLE COMPACTION_QUEUE MODIFY (
  CQ_ID NUMBER(19),
  CQ_START NUMBER(19)
);

ALTER TABLE NEXT_COMPACTION_QUEUE_ID MODIFY (
  NCQ_NEXT NUMBER(19)
);
