ALTER TABLE COLUMNS_V2 MODIFY (
  "COLUMN_NAME" VARCHAR2(1000)
);

ALTER TABLE PART_COL_PRIVS MODIFY (
  "COLUMN_NAME" VARCHAR2(1000)
);

ALTER TABLE TBL_COL_PRIVS MODIFY (
  "COLUMN_NAME" VARCHAR2(1000)
);

ALTER TABLE SORT_COLS MODIFY (
  "COLUMN_NAME" VARCHAR2(1000)
);

ALTER TABLE TAB_COL_STATS MODIFY (
  "COLUMN_NAME" VARCHAR2(1000)
);

ALTER TABLE PART_COL_STATS MODIFY (
  "COLUMN_NAME" VARCHAR2(1000)
);