SELECT 'Upgrading MetaStore schema from 0.12.0 to 0.13.0' AS Status from dual;

CREATE FUNCTION hive13_to_date(date_str IN VARCHAR2)
RETURN DATE
IS dt DATE;
BEGIN
  dt := TO_DATE(date_str, 'YYYY-MM-DD');
  RETURN dt;
EXCEPTION
  WHEN others THEN RETURN null;
END;
/

MERGE INTO PARTITION_KEY_VALS
USING (
  SELECT SRC.PART_ID as IPART_ID, SRC.INTEGER_IDX as IINTEGER_IDX, 
     NVL(TO_CHAR(hive13_to_date(PART_KEY_VAL),'YYYY-MM-DD'), PART_KEY_VAL) as NORM
  FROM PARTITION_KEY_VALS SRC
    INNER JOIN PARTITIONS ON SRC.PART_ID = PARTITIONS.PART_ID
    INNER JOIN PARTITION_KEYS ON PARTITION_KEYS.TBL_ID = PARTITIONS.TBL_ID
      AND PARTITION_KEYS.INTEGER_IDX = SRC.INTEGER_IDX AND PARTITION_KEYS.PKEY_TYPE = 'date'
) ON (IPART_ID = PARTITION_KEY_VALS.PART_ID AND IINTEGER_IDX = PARTITION_KEY_VALS.INTEGER_IDX)
WHEN MATCHED THEN UPDATE SET PART_KEY_VAL = NORM;

DROP FUNCTION hive13_to_date;

UPDATE VERSION SET SCHEMA_VERSION='0.13.0', VERSION_COMMENT='Hive release version 0.13.0' where VER_ID=1;
SELECT 'Finished upgrading MetaStore schema from 0.12.0 to 0.13.0' AS Status from dual;
