--
-- Licensed to the Apache Software Foundation (ASF) under one or more
-- contributor license agreements.  See the NOTICE file distributed with
-- this work for additional information regarding copyright ownership.
-- The ASF licenses this file to you under the Apache License, Version 2.0
-- (the "License"); you may not use this file except in compliance with
-- the License.  You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- Rebuilds all HMS indexes on Derby (plain DROP INDEX; Derby has no IF EXISTS).

DROP INDEX NOTIFICATION_LOG_EVENT_ID;
CREATE UNIQUE INDEX NOTIFICATION_LOG_EVENT_ID ON NOTIFICATION_LOG ("EVENT_ID");

DROP INDEX TABLECOLUMNPRIVILEGEINDEX;
CREATE INDEX TABLECOLUMNPRIVILEGEINDEX ON TBL_COL_PRIVS ("AUTHORIZER", "TBL_ID", "COLUMN_NAME", "PRINCIPAL_NAME", "PRINCIPAL_TYPE", "TBL_COL_PRIV", "GRANTOR", "GRANTOR_TYPE");

DROP INDEX DBPRIVILEGEINDEX;
CREATE UNIQUE INDEX DBPRIVILEGEINDEX ON DB_PRIVS ("AUTHORIZER", "DB_ID", "PRINCIPAL_NAME", "PRINCIPAL_TYPE", "DB_PRIV", "GRANTOR", "GRANTOR_TYPE");

DROP INDEX DCPRIVILEGEINDEX;
CREATE UNIQUE INDEX DCPRIVILEGEINDEX ON DC_PRIVS ("AUTHORIZER", "NAME", "PRINCIPAL_NAME", "PRINCIPAL_TYPE", "DC_PRIV", "GRANTOR", "GRANTOR_TYPE");

DROP INDEX PCS_STATS_IDX;
CREATE INDEX PCS_STATS_IDX ON PART_COL_STATS ("PART_ID", "COLUMN_NAME");

DROP INDEX TAB_COL_STATS_IDX;
CREATE INDEX TAB_COL_STATS_IDX ON TAB_COL_STATS ("TBL_ID", "COLUMN_NAME");

DROP INDEX PARTPRIVILEGEINDEX;
CREATE INDEX PARTPRIVILEGEINDEX ON PART_PRIVS ("AUTHORIZER", "PART_ID", "PRINCIPAL_NAME", "PRINCIPAL_TYPE", "PART_PRIV", "GRANTOR", "GRANTOR_TYPE");

DROP INDEX ROLEENTITYINDEX;
CREATE UNIQUE INDEX ROLEENTITYINDEX ON ROLES ("ROLE_NAME");

DROP INDEX TABLEPRIVILEGEINDEX;
CREATE INDEX TABLEPRIVILEGEINDEX ON TBL_PRIVS ("AUTHORIZER", "TBL_ID", "PRINCIPAL_NAME", "PRINCIPAL_TYPE", "TBL_PRIV", "GRANTOR", "GRANTOR_TYPE");

DROP INDEX UNIQUETABLE;
CREATE UNIQUE INDEX UNIQUETABLE ON TBLS ("DB_ID", "TBL_NAME");

DROP INDEX UNIQUE_DATABASE;
CREATE UNIQUE INDEX UNIQUE_DATABASE ON DBS ("NAME", "CTLG_NAME");

DROP INDEX USERROLEMAPINDEX;
CREATE UNIQUE INDEX USERROLEMAPINDEX ON ROLE_MAP ("PRINCIPAL_NAME", "ROLE_ID", "GRANTOR", "GRANTOR_TYPE");

DROP INDEX GLOBALPRIVILEGEINDEX;
CREATE UNIQUE INDEX GLOBALPRIVILEGEINDEX ON GLOBAL_PRIVS ("AUTHORIZER", "PRINCIPAL_NAME", "PRINCIPAL_TYPE", "USER_PRIV", "GRANTOR", "GRANTOR_TYPE");

DROP INDEX UNIQUE_TYPE;
CREATE UNIQUE INDEX UNIQUE_TYPE ON TYPES ("TYPE_NAME");

DROP INDEX PARTITIONCOLUMNPRIVILEGEINDEX;
CREATE INDEX PARTITIONCOLUMNPRIVILEGEINDEX ON PART_COL_PRIVS ("AUTHORIZER", "PART_ID", "COLUMN_NAME", "PRINCIPAL_NAME", "PRINCIPAL_TYPE", "PART_COL_PRIV", "GRANTOR", "GRANTOR_TYPE");

DROP INDEX UNIQUEPARTITION;
CREATE UNIQUE INDEX UNIQUEPARTITION ON PARTITIONS ("TBL_ID", "PART_NAME");

DROP INDEX UNIQUEFUNCTION;
CREATE UNIQUE INDEX UNIQUEFUNCTION ON FUNCS ("FUNC_NAME", "DB_ID");

DROP INDEX FUNCS_N49;
CREATE INDEX FUNCS_N49 ON FUNCS ("DB_ID");

DROP INDEX FUNC_RU_N49;
CREATE INDEX FUNC_RU_N49 ON FUNC_RU ("FUNC_ID");

DROP INDEX CONSTRAINTS_PARENT_TBL_ID_INDEX;
CREATE INDEX CONSTRAINTS_PARENT_TBL_ID_INDEX ON KEY_CONSTRAINTS ("PARENT_TBL_ID");

DROP INDEX CONSTRAINTS_CONSTRAINT_TYPE_INDEX;
CREATE INDEX CONSTRAINTS_CONSTRAINT_TYPE_INDEX ON KEY_CONSTRAINTS ("CONSTRAINT_TYPE");

DROP INDEX UNIQUE_WM_RESOURCEPLAN;
CREATE UNIQUE INDEX UNIQUE_WM_RESOURCEPLAN ON WM_RESOURCEPLAN ("NS", "NAME");

DROP INDEX UNIQUE_WM_POOL;
CREATE UNIQUE INDEX UNIQUE_WM_POOL ON WM_POOL ("RP_ID", "PATH");

DROP INDEX UNIQUE_WM_TRIGGER;
CREATE UNIQUE INDEX UNIQUE_WM_TRIGGER ON WM_TRIGGER ("RP_ID", "NAME");

DROP INDEX UNIQUE_WM_MAPPING;
CREATE UNIQUE INDEX UNIQUE_WM_MAPPING ON WM_MAPPING ("RP_ID", "ENTITY_TYPE", "ENTITY_NAME");

DROP INDEX MV_UNIQUE_TABLE;
CREATE UNIQUE INDEX MV_UNIQUE_TABLE ON MV_CREATION_METADATA ("TBL_NAME", "DB_NAME");

DROP INDEX UNIQUE_CATALOG;
CREATE UNIQUE INDEX UNIQUE_CATALOG ON CTLGS ("NAME");

DROP INDEX TC_TXNID_INDEX;
CREATE INDEX TC_TXNID_INDEX ON TXN_COMPONENTS (TC_TXNID);

DROP INDEX COMPLETED_TXN_COMPONENTS_IDX;
CREATE INDEX COMPLETED_TXN_COMPONENTS_IDX ON COMPLETED_TXN_COMPONENTS (CTC_DATABASE, CTC_TABLE, CTC_PARTITION);

DROP INDEX HL_TXNID_INDEX;
CREATE INDEX HL_TXNID_INDEX ON HIVE_LOCKS (HL_TXNID);

DROP INDEX COMPLETED_COMPACTIONS_RES;
CREATE INDEX COMPLETED_COMPACTIONS_RES ON COMPLETED_COMPACTIONS (CC_DATABASE, CC_TABLE, CC_PARTITION);

DROP INDEX TBL_TO_TXN_ID_IDX;
CREATE UNIQUE INDEX TBL_TO_TXN_ID_IDX ON TXN_TO_WRITE_ID (T2W_DATABASE, T2W_TABLE, T2W_TXNID);

DROP INDEX TBL_TO_WRITE_ID_IDX;
CREATE UNIQUE INDEX TBL_TO_WRITE_ID_IDX ON TXN_TO_WRITE_ID (T2W_DATABASE, T2W_TABLE, T2W_WRITEID);

DROP INDEX NEXT_WRITE_ID_IDX;
CREATE UNIQUE INDEX NEXT_WRITE_ID_IDX ON NEXT_WRITE_ID (NWI_DATABASE, NWI_TABLE);

DROP INDEX MIN_HISTORY_WRITE_ID_IDX;
CREATE INDEX MIN_HISTORY_WRITE_ID_IDX ON MIN_HISTORY_WRITE_ID (MH_DATABASE, MH_TABLE, MH_WRITEID);

DROP INDEX MIN_HISTORY_LEVEL_IDX;
CREATE INDEX MIN_HISTORY_LEVEL_IDX ON MIN_HISTORY_LEVEL (MHL_MIN_OPEN_TXNID);

DROP INDEX UNIQUE_SCHEMA_VERSION;
CREATE UNIQUE INDEX UNIQUE_SCHEMA_VERSION ON SCHEMA_VERSION ("SCHEMA_ID", "VERSION");

DROP INDEX IDX_RUNTIME_STATS_CREATE_TIME;
CREATE INDEX IDX_RUNTIME_STATS_CREATE_TIME ON RUNTIME_STATS (CREATE_TIME);

DROP INDEX NEXTEXECUTIONINDEX;
CREATE INDEX NEXTEXECUTIONINDEX ON SCHEDULED_QUERIES (ENABLED, CLUSTER_NAMESPACE, NEXT_EXECUTION);

DROP INDEX UNIQUE_SCHEDULED_QUERIES_NAME;
CREATE UNIQUE INDEX UNIQUE_SCHEDULED_QUERIES_NAME ON SCHEDULED_QUERIES (SCHEDULE_NAME, CLUSTER_NAMESPACE);

DROP INDEX LASTUPDATETIMEINDEX;
CREATE INDEX LASTUPDATETIMEINDEX ON SCHEDULED_EXECUTIONS (LAST_UPDATE_TIME);

DROP INDEX SCHEDULED_EXECUTIONS_SCHQID;
CREATE INDEX SCHEDULED_EXECUTIONS_SCHQID ON SCHEDULED_EXECUTIONS (SCHEDULED_QUERY_ID);

DROP INDEX SCHEDULED_EXECUTIONS_UNIQUE_ID;
CREATE UNIQUE INDEX SCHEDULED_EXECUTIONS_UNIQUE_ID ON SCHEDULED_EXECUTIONS (SCHEDULED_EXECUTION_ID);

DROP INDEX POLICY_IDX;
CREATE INDEX POLICY_IDX ON REPLICATION_METRICS ("RM_POLICY");

DROP INDEX DUMP_IDX;
CREATE INDEX DUMP_IDX ON REPLICATION_METRICS ("RM_DUMP_EXECUTION_ID");

DROP INDEX UNIQUESTOREDPROC;
CREATE UNIQUE INDEX UNIQUESTOREDPROC ON STORED_PROCS ("NAME", "DB_ID");

DROP INDEX UNIQUEPKG;
CREATE UNIQUE INDEX UNIQUEPKG ON PACKAGES ("NAME", "DB_ID");

