-- HIVE-27725
DROP INDEX "APP"."TAB_COL_STATS_IDX";
CREATE INDEX "APP"."TAB_COL_STATS_IDX" ON "APP"."TAB_COL_STATS" ("TBL_ID", "COLUMN_NAME");
ALTER TABLE "APP"."TAB_COL_STATS" DROP COLUMN "CAT_NAME";
ALTER TABLE "APP"."TAB_COL_STATS" DROP COLUMN "DB_NAME";
ALTER TABLE "APP"."TAB_COL_STATS" DROP COLUMN "TABLE_NAME";

DROP INDEX "APP"."PCS_STATS_IDX";
CREATE INDEX "APP"."PCS_STATS_IDX" ON "APP"."PART_COL_STATS" ("PART_ID","COLUMN_NAME");
ALTER TABLE "APP"."PART_COL_STATS" DROP COLUMN "CAT_NAME";
ALTER TABLE "APP"."PART_COL_STATS" DROP COLUMN "DB_NAME";
ALTER TABLE "APP"."PART_COL_STATS" DROP COLUMN "TABLE_NAME";
ALTER TABLE "APP"."PART_COL_STATS" DROP COLUMN "PARTITION_NAME";

-- HIVE-28292
DROP INDEX "APP"."UNIQUETABLE";
CREATE UNIQUE INDEX "APP"."UNIQUETABLE" ON "APP"."TBLS" ("DB_ID", "TBL_NAME");

-- This needs to be the last thing done.  Insert any changes above this line.
UPDATE "APP".VERSION SET SCHEMA_VERSION='4.1.0', VERSION_COMMENT='Hive release version 4.1.0' where VER_ID=1;