-- HIVE-27725
DROP INDEX "APP"."TAB_COL_STATS_IDX";
CREATE INDEX "APP"."TAB_COL_STATS_IDX" ON "APP"."TAB_COL_STATS" ("TBL_ID", "COLUMN_NAME");
ALTER TABLE "APP"."TAB_COL_STATS" DROP COLUMN "CAT_NAME";
ALTER TABLE "APP"."TAB_COL_STATS" DROP COLUMN "DB_NAME";
ALTER TABLE "APP"."TAB_COL_STATS" DROP COLUMN "TABLE_NAME";

DROP INDEX "APP"."PCS_STATS_IDX";
CREATE INDEX "APP"."PCS_STATS_IDX" ON "APP"."PART_COL_STATS" ("PART_ID","COLUMN_NAME");
ALTER TABLE "APP"."PART_COL_STATS" DROP COLUMN "CAT_NAME";
ALTER TABLE "APP"."PART_COL_STATS" DROP COLUMN "DB_NAME";
ALTER TABLE "APP"."PART_COL_STATS" DROP COLUMN "TABLE_NAME";
ALTER TABLE "APP"."PART_COL_STATS" DROP COLUMN "PARTITION_NAME";

-- HIVE-28292
DROP INDEX "APP"."UNIQUETABLE";
CREATE UNIQUE INDEX "APP"."UNIQUETABLE" ON "APP"."TBLS" ("DB_ID", "TBL_NAME");

-- HIVE-17306
ALTER TABLE "COMPLETED_TXN_COMPONENTS" ADD COLUMN "INV_ID" BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY;
ALTER TABLE "NEXT_COMPACTION_QUEUE_ID" ADD CONSTRAINT "NEXT_COMPACTION_QUEUE_ID_PK" PRIMARY KEY ("NCQ_NEXT");
ALTER TABLE "NEXT_LOCK_ID" ADD CONSTRAINT "NEXT_LOCK_ID_PK" PRIMARY KEY ("NL_NEXT");
ALTER TABLE "TXN_LOCK_TBL" ADD CONSTRAINT "TXN_LOCK_TBL_PK" PRIMARY KEY ("TXN_LOCK");
ALTER TABLE "NEXT_WRITE_ID" ADD CONSTRAINT "NEXT_WRITE_ID_PK" PRIMARY KEY ("NWI_TABLE", "NWI_DATABASE");
ALTER TABLE "TXN_COMPONENTS" ADD COLUMN "INV_ID" BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY;
ALTER TABLE "TXN_TO_WRITE_ID" ADD CONSTRAINT "TXN_TO_WRITE_ID_PK" PRIMARY KEY ("T2W_TXNID", "T2W_DATABASE", "T2W_TABLE");
ALTER TABLE "WRITE_SET" ADD COLUMN "INV_ID" BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY;
ALTER TABLE "COMPACTION_METRICS_CACHE" ADD COLUMN "INV_ID" BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY;
ALTER TABLE "MIN_HISTORY_WRITE_ID" ADD CONSTRAINT "MIN_HISTORY_WRITE_ID_PK" PRIMARY KEY (MH_TXNID, MH_DATABASE, MH_TABLE, MH_WRITEID);

-- This needs to be the last thing done.  Insert any changes above this line.
UPDATE "APP".VERSION SET SCHEMA_VERSION='4.1.0', VERSION_COMMENT='Hive release version 4.1.0' where VER_ID=1;