-- Table PARTITION_EVENTS for classes [org.apache.hadoop.hive.metastore.model.MPartitionEvent]
CREATE TABLE PARTITION_EVENTS
(
    PART_NAME_ID BIGINT NOT NULL,
    DB_NAME VARCHAR(128),
    EVENT_TIME BIGINT NOT NULL,
    EVENT_TYPE INTEGER NOT NULL,
    PARTITION_NAME VARCHAR(767),
    TBL_NAME VARCHAR(128)
);

ALTER TABLE PARTITION_EVENTS ADD CONSTRAINT PARTITION_EVENTS_PK PRIMARY KEY (PART_NAME_ID);

