CREATE TABLE "APP"."CHANGE_VERSION" ("CHANGE_VERSION_ID" BIGINT NOT NULL, "VERSION" BIGINT NOT NULL, "TOPIC" VARCHAR(255));
ALTER TABLE "APP"."CHANGE_VERSION" ADD CONSTRAINT "CHANGE_VERSION_PK" PRIMARY KEY ("CHANGE_VERSION_ID");
CREATE UNIQUE INDEX "APP"."UNIQUECHANGEVERSION" ON "APP"."CHANGE_VERSION" ("TOPIC");
