/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef serde_TYPES_H
#define serde_TYPES_H

#include <Thrift.h>
#include <protocol/TProtocol.h>
#include <transport/TTransport.h>



namespace Hive {

typedef std::string PrimitiveType;

typedef std::string CollectionType;

} // namespace

#endif
