-- Create stored procedure tables
CREATE TABLE "STORED_PROCS" (
  "SP_ID" BIGINT NOT NULL,
  "CREATE_TIME" int NOT NULL,
  "DB_ID" BIGINT NOT NULL,
  "NAME" nvarchar(256) NOT NULL,
  "OWNER_NAME" nvarchar(128) NOT NULL,
  "SOURCE" NTEXT NOT NULL,
  PRIMARY KEY ("SP_ID")
);

CREATE UNIQUE INDEX "UNIQUESTOREDPROC" ON "STORED_PROCS" ("NAME", "DB_ID");
ALTER TABLE "STORED_PROCS" ADD CONSTRAINT "STOREDPROC_FK1" FOREIGN KEY ("DB_ID") REFERENCES "DBS" ("DB_ID");

-- Create stored procedure packages
CREATE TABLE "PACKAGES" (
  "PKG_ID" BIGINT NOT NULL,
  "CREATE_TIME" int NOT NULL,
  "DB_ID" BIGINT NOT NULL,
  "NAME" nvarchar(256) NOT NULL,
  "OWNER_NAME" nvarchar(128) NOT NULL,
  "HEADER" NTEXT NOT NULL,
  "BODY" NTEXT NOT NULL,
  PRIMARY KEY ("PKG_ID")
);

CREATE UNIQUE INDEX "UNIQUEPKG" ON "PACKAGES" ("NAME", "DB_ID");
ALTER TABLE "PACKAGES" ADD CONSTRAINT "PACKAGES_FK1" FOREIGN KEY ("DB_ID") REFERENCES "DBS" ("DB_ID");

-- These lines need to be last.  Insert any changes above.
UPDATE CDH_VERSION SET SCHEMA_VERSION='3.1.3000.7.2.11.0-Update1', VERSION_COMMENT='Hive release version 3.1.3000 for CDH 7.2.11.0-Update1' where VER_ID=1;
SELECT 'Finished upgrading MetaStore schema from 3.1.3000.7.2.10.0-Update1 to 3.1.3000.7.2.11.0-Update1' AS MESSAGE;
