--ALTER PARTITIONS.PART_NAME from varchar to nvarchar
DROP INDEX PARTITIONS.UNIQUEPARTITION;
ALTER TABLE PARTITIONS ALTER COLUMN PART_NAME NVARCHAR(767) NULL;
CREATE UNIQUE INDEX UNIQUEPARTITION ON PARTITIONS (PART_NAME,TBL_ID);

--ALTER SDS.LOCATION from varchar to nvarchar
ALTER TABLE SDS ALTER COLUMN LOCATION NVARCHAR(4000) NULL;

--ALTER PARTITION_KEY_VALS.PART_KEY_VAL from varchar to nvarchar
ALTER TABLE PARTITION_KEY_VALS ALTER COLUMN PART_KEY_VAL NVARCHAR(255) NULL;
