CREATE TABLE MV_CREATION_METADATA
(
    TBL_ID bigint NOT NULL,
    TBL_NAME nvarchar(256) NOT NULL,
    LAST_TRANSACTION_INFO text NOT NULL
);
ALTER TABLE MV_CREATION_METADATA ADD CONSTRAINT MV_CREATION_METADATA_FK FOREIGN KEY (TBL_ID) REFERENCES TBLS (TBL_ID);

CREATE TABLE COMPLETED_TXN_COMPONENTS_NEW(
	CTC_TXNID bigint NULL,
	CTC_DATABASE varchar(128) NOT NULL,
	CTC_TABLE varchar(256) NULL,
	CTC_PARTITION varchar(767) NULL,
	CTC_ID bigint GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
	CTC_TIMESTAMP timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX COMPLETED_TXN_COMPONENTS_IDX ON COMPLETED_TXN_COMPONENTS_NEW (CTC_ID);
CREATE INDEX COMPLETED_TXN_COMPONENTS_IDX2 ON COMPLETED_TXN_COMPONENTS_NEW (CTC_DATABASE, CTC_TABLE, CTC_PARTITION);
INSERT INTO COMPLETED_TXN_COMPONENTS_NEW (CTC_TXNID, CTC_DATABASE, CTC_TABLE, CTC_PARTITION)
SELECT CTC_TXNID, CTC_DATABASE, CTC_TABLE, CTC_PARTITION FROM COMPLETED_TXN_COMPONENTS;
exec sp_rename 'COMPLETED_TXN_COMPONENTS', 'COMPLETED_TXN_COMPONENTS_BACKUP';
exec sp_rename 'COMPLETED_TXN_COMPONENTS_NEW', 'COMPLETED_TXN_COMPONENTS';
DROP TABLE COMPLETED_TXN_COMPONENTS_BACKUP;
