/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef hive_metastore_CONSTANTS_H
#define hive_metastore_CONSTANTS_H

#include "hive_metastore_types.h"

namespace Apache { namespace Hadoop { namespace Hive {

class hive_metastoreConstants {
 public:
  hive_metastoreConstants();

  std::string META_TABLE_COLUMNS;
  std::string META_TABLE_COLUMN_TYPES;
  std::string BUCKET_FIELD_NAME;
  std::string BUCKET_COUNT;
  std::string FIELD_TO_DIMENSION;
  std::string META_TABLE_NAME;
  std::string META_TABLE_DB;
  std::string META_TABLE_LOCATION;
  std::string META_TABLE_SERDE;
  std::string META_TABLE_PARTITION_COLUMNS;
  std::string FILE_INPUT_FORMAT;
  std::string FILE_OUTPUT_FORMAT;
};

extern const hive_metastoreConstants g_hive_metastore_constants;

}}} // namespace

#endif
