/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "hive_metastore_constants.h"

namespace Apache { namespace Hadoop { namespace Hive {

const hive_metastoreConstants g_hive_metastore_constants;

hive_metastoreConstants::hive_metastoreConstants() {
  META_TABLE_COLUMNS = "columns";

  META_TABLE_COLUMN_TYPES = "columns.types";

  BUCKET_FIELD_NAME = "bucket_field_name";

  BUCKET_COUNT = "bucket_count";

  FIELD_TO_DIMENSION = "field_to_dimension";

  META_TABLE_NAME = "name";

  META_TABLE_DB = "db";

  META_TABLE_LOCATION = "location";

  META_TABLE_SERDE = "serde";

  META_TABLE_PARTITION_COLUMNS = "partition_columns";

  FILE_INPUT_FORMAT = "file.inputformat";

  FILE_OUTPUT_FORMAT = "file.outputformat";

}

}}} // namespace

