--
-- Licensed to the Apache Software Foundation (ASF) under one or more
-- contributor license agreements.  See the NOTICE file distributed with
-- this work for additional information regarding copyright ownership.
-- The ASF licenses this file to you under the Apache License, Version 2.0
-- (the "License"); you may not use this file except in compliance with
-- the License.  You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.


-- Rebuilds all HMS indexes on MySQL using ALTER TABLE for atomicity.
-- Update this file whenever a new upgrade script adds an index.

ALTER TABLE `BUCKETING_COLS` DROP INDEX `BUCKETING_COLS_N49`, ADD INDEX `BUCKETING_COLS_N49` (`SD_ID`);

ALTER TABLE `COLUMNS_V2` DROP INDEX `COLUMNS_V2_N49`, ADD INDEX `COLUMNS_V2_N49` (`CD_ID`);

ALTER TABLE `COMPLETED_COMPACTIONS` DROP INDEX `COMPLETED_COMPACTIONS_RES`, ADD INDEX `COMPLETED_COMPACTIONS_RES` (CC_DATABASE,CC_TABLE,CC_PARTITION);

ALTER TABLE `COMPLETED_TXN_COMPONENTS` DROP INDEX `COMPLETED_TXN_COMPONENTS_IDX`, ADD INDEX `COMPLETED_TXN_COMPONENTS_IDX` (CTC_DATABASE, CTC_TABLE, CTC_PARTITION);

ALTER TABLE `KEY_CONSTRAINTS` DROP INDEX `CONSTRAINTS_CONSTRAINT_TYPE_INDEX`, ADD INDEX `CONSTRAINTS_CONSTRAINT_TYPE_INDEX` (`CONSTRAINT_TYPE`);

ALTER TABLE `KEY_CONSTRAINTS` DROP INDEX `CONSTRAINTS_PARENT_TABLE_ID_INDEX`, ADD INDEX `CONSTRAINTS_PARENT_TABLE_ID_INDEX` (`PARENT_TBL_ID`);

ALTER TABLE `DATABASE_PARAMS` DROP INDEX `DATABASE_PARAMS_N49`, ADD INDEX `DATABASE_PARAMS_N49` (`DB_ID`);

ALTER TABLE `DB_PRIVS` DROP INDEX `DBPRIVILEGEINDEX`, ADD UNIQUE INDEX `DBPRIVILEGEINDEX` (`AUTHORIZER`,`DB_ID`,`PRINCIPAL_NAME`,`PRINCIPAL_TYPE`,`DB_PRIV`,`GRANTOR`,`GRANTOR_TYPE`);

ALTER TABLE `DB_PRIVS` DROP INDEX `DB_PRIVS_N49`, ADD INDEX `DB_PRIVS_N49` (`DB_ID`);

ALTER TABLE `DC_PRIVS` DROP INDEX `DCPRIVILEGEINDEX`, ADD UNIQUE INDEX `DCPRIVILEGEINDEX` (`AUTHORIZER`,`NAME`,`PRINCIPAL_NAME`,`PRINCIPAL_TYPE`,`DC_PRIV`,`GRANTOR`,`GRANTOR_TYPE`);

ALTER TABLE `DC_PRIVS` DROP INDEX `DC_PRIVS_N49`, ADD INDEX `DC_PRIVS_N49` (`NAME`);

ALTER TABLE `REPLICATION_METRICS` DROP INDEX `DUMP_IDX`, ADD INDEX `DUMP_IDX` (RM_DUMP_EXECUTION_ID);

ALTER TABLE `FUNCS` DROP INDEX `FUNCS_N49`, ADD INDEX `FUNCS_N49` (`DB_ID`);

ALTER TABLE `GLOBAL_PRIVS` DROP INDEX `GLOBALPRIVILEGEINDEX`, ADD UNIQUE INDEX `GLOBALPRIVILEGEINDEX` (`AUTHORIZER`,`PRINCIPAL_NAME`,`PRINCIPAL_TYPE`,`USER_PRIV`,`GRANTOR`,`GRANTOR_TYPE`);

ALTER TABLE `HIVE_LOCKS` DROP INDEX `HIVE_LOCK_TXNID_INDEX`, ADD INDEX `HIVE_LOCK_TXNID_INDEX` (HL_TXNID);

ALTER TABLE `HIVE_LOCKS` DROP INDEX `HL_TXNID_IDX`, ADD INDEX `HL_TXNID_IDX` (HL_TXNID);

ALTER TABLE `RUNTIME_STATS` DROP INDEX `IDX_RUNTIME_STATS_CREATE_TIME`, ADD INDEX `IDX_RUNTIME_STATS_CREATE_TIME` (CREATE_TIME);

ALTER TABLE `SCHEDULED_EXECUTIONS` DROP INDEX `IDX_SCHEDULED_EXECUTIONS_LAST_UPDATE_TIME`, ADD INDEX `IDX_SCHEDULED_EXECUTIONS_LAST_UPDATE_TIME` (LAST_UPDATE_TIME);

ALTER TABLE `SCHEDULED_EXECUTIONS` DROP INDEX `IDX_SCHEDULED_EXECUTIONS_SCHEDULED_QUERY_ID`, ADD INDEX `IDX_SCHEDULED_EXECUTIONS_SCHEDULED_QUERY_ID` (SCHEDULED_QUERY_ID);

ALTER TABLE `MIN_HISTORY_LEVEL` DROP INDEX `MIN_HISTORY_LEVEL_IDX`, ADD INDEX `MIN_HISTORY_LEVEL_IDX` (MHL_MIN_OPEN_TXNID);

ALTER TABLE `MIN_HISTORY_WRITE_ID` DROP INDEX `MIN_HISTORY_WRITE_ID_IDX`, ADD INDEX `MIN_HISTORY_WRITE_ID_IDX` (MH_DATABASE, MH_TABLE, MH_WRITEID);

ALTER TABLE `MV_CREATION_METADATA` DROP INDEX `MV_UNIQUE_TABLE`, ADD INDEX `MV_UNIQUE_TABLE` (TBL_NAME, DB_NAME);

ALTER TABLE `NEXT_WRITE_ID` DROP INDEX `NEXT_WRITE_ID_IDX`, ADD UNIQUE INDEX `NEXT_WRITE_ID_IDX` (NWI_DATABASE, NWI_TABLE);

ALTER TABLE `NOTIFICATION_LOG` DROP INDEX `NOTIFICATION_LOG_EVENT_ID`, ADD UNIQUE INDEX `NOTIFICATION_LOG_EVENT_ID` (`EVENT_ID`);

ALTER TABLE `PART_COL_PRIVS` DROP INDEX `PARTITIONCOLUMNPRIVILEGEINDEX`, ADD INDEX `PARTITIONCOLUMNPRIVILEGEINDEX` (`AUTHORIZER`,`PART_ID`,`COLUMN_NAME`,`PRINCIPAL_NAME`,`PRINCIPAL_TYPE`,`PART_COL_PRIV`,`GRANTOR`,`GRANTOR_TYPE`);

ALTER TABLE `PARTITION_EVENTS` DROP INDEX `PARTITIONEVENTINDEX`, ADD INDEX `PARTITIONEVENTINDEX` (`PARTITION_NAME`);

ALTER TABLE `PARTITIONS` DROP INDEX `PARTITIONS_N50`, ADD INDEX `PARTITIONS_N50` (`SD_ID`);

ALTER TABLE `PARTITION_KEYS` DROP INDEX `PARTITION_KEYS_N49`, ADD INDEX `PARTITION_KEYS_N49` (`TBL_ID`);

ALTER TABLE `PARTITION_KEY_VALS` DROP INDEX `PARTITION_KEY_VALS_N49`, ADD INDEX `PARTITION_KEY_VALS_N49` (`PART_ID`);

ALTER TABLE `PARTITION_PARAMS` DROP INDEX `PARTITION_PARAMS_N49`, ADD INDEX `PARTITION_PARAMS_N49` (`PART_ID`);

ALTER TABLE `PART_PRIVS` DROP INDEX `PARTPRIVILEGEINDEX`, ADD INDEX `PARTPRIVILEGEINDEX` (`AUTHORIZER`,`PART_ID`,`PRINCIPAL_NAME`,`PRINCIPAL_TYPE`,`PART_PRIV`,`GRANTOR`,`GRANTOR_TYPE`);

ALTER TABLE `PART_COL_PRIVS` DROP INDEX `PART_COL_PRIVS_N49`, ADD INDEX `PART_COL_PRIVS_N49` (`PART_ID`);

ALTER TABLE `PART_PRIVS` DROP INDEX `PART_PRIVS_N49`, ADD INDEX `PART_PRIVS_N49` (`PART_ID`);

ALTER TABLE `PART_COL_STATS` DROP INDEX `PCS_STATS_IDX`, ADD INDEX `PCS_STATS_IDX` (PART_ID,COLUMN_NAME);

ALTER TABLE `REPLICATION_METRICS` DROP INDEX `POLICY_IDX`, ADD INDEX `POLICY_IDX` (RM_POLICY);

ALTER TABLE `ROLES` DROP INDEX `ROLEENTITYINDEX`, ADD UNIQUE INDEX `ROLEENTITYINDEX` (`ROLE_NAME`);

ALTER TABLE `ROLE_MAP` DROP INDEX `ROLE_MAP_N49`, ADD INDEX `ROLE_MAP_N49` (`ROLE_ID`);

ALTER TABLE `SDS` DROP INDEX `SDS_N49`, ADD INDEX `SDS_N49` (`SERDE_ID`);

ALTER TABLE `SDS` DROP INDEX `SDS_N50`, ADD INDEX `SDS_N50` (`CD_ID`);

ALTER TABLE `SD_PARAMS` DROP INDEX `SD_PARAMS_N49`, ADD INDEX `SD_PARAMS_N49` (`SD_ID`);

ALTER TABLE `SERDE_PARAMS` DROP INDEX `SERDE_PARAMS_N49`, ADD INDEX `SERDE_PARAMS_N49` (`SERDE_ID`);

ALTER TABLE `SKEWED_COL_NAMES` DROP INDEX `SKEWED_COL_NAMES_N49`, ADD INDEX `SKEWED_COL_NAMES_N49` (`SD_ID`);

ALTER TABLE `SKEWED_COL_VALUE_LOC_MAP` DROP INDEX `SKEWED_COL_VALUE_LOC_MAP_N49`, ADD INDEX `SKEWED_COL_VALUE_LOC_MAP_N49` (`STRING_LIST_ID_KID`);

ALTER TABLE `SKEWED_COL_VALUE_LOC_MAP` DROP INDEX `SKEWED_COL_VALUE_LOC_MAP_N50`, ADD INDEX `SKEWED_COL_VALUE_LOC_MAP_N50` (`SD_ID`);

ALTER TABLE `SKEWED_STRING_LIST_VALUES` DROP INDEX `SKEWED_STRING_LIST_VALUES_N49`, ADD INDEX `SKEWED_STRING_LIST_VALUES_N49` (`STRING_LIST_ID`);

ALTER TABLE `SKEWED_VALUES` DROP INDEX `SKEWED_VALUES_N49`, ADD INDEX `SKEWED_VALUES_N49` (`STRING_LIST_ID_EID`);

ALTER TABLE `SKEWED_VALUES` DROP INDEX `SKEWED_VALUES_N50`, ADD INDEX `SKEWED_VALUES_N50` (`SD_ID_OID`);

ALTER TABLE `SORT_COLS` DROP INDEX `SORT_COLS_N49`, ADD INDEX `SORT_COLS_N49` (`SD_ID`);

ALTER TABLE `TBL_COL_PRIVS` DROP INDEX `TABLECOLUMNPRIVILEGEINDEX`, ADD INDEX `TABLECOLUMNPRIVILEGEINDEX` (`AUTHORIZER`,`TBL_ID`,`COLUMN_NAME`,`PRINCIPAL_NAME`,`PRINCIPAL_TYPE`,`TBL_COL_PRIV`,`GRANTOR`,`GRANTOR_TYPE`);

ALTER TABLE `TBL_PRIVS` DROP INDEX `TABLEPRIVILEGEINDEX`, ADD INDEX `TABLEPRIVILEGEINDEX` (`AUTHORIZER`,`TBL_ID`,`PRINCIPAL_NAME`,`PRINCIPAL_TYPE`,`TBL_PRIV`,`GRANTOR`,`GRANTOR_TYPE`);

ALTER TABLE `TABLE_PARAMS` DROP INDEX `TABLE_PARAMS_N49`, ADD INDEX `TABLE_PARAMS_N49` (`TBL_ID`);

ALTER TABLE `TAB_COL_STATS` DROP INDEX `TAB_COL_STATS_IDX`, ADD INDEX `TAB_COL_STATS_IDX` (TBL_ID, COLUMN_NAME);

ALTER TABLE `TBLS` DROP INDEX `TBLS_N50`, ADD INDEX `TBLS_N50` (`SD_ID`);

ALTER TABLE `TBL_COL_PRIVS` DROP INDEX `TBL_COL_PRIVS_N49`, ADD INDEX `TBL_COL_PRIVS_N49` (`TBL_ID`);

ALTER TABLE `TBL_PRIVS` DROP INDEX `TBL_PRIVS_N49`, ADD INDEX `TBL_PRIVS_N49` (`TBL_ID`);

ALTER TABLE `TXN_TO_WRITE_ID` DROP INDEX `TBL_TO_TXN_ID_IDX`, ADD UNIQUE INDEX `TBL_TO_TXN_ID_IDX` (T2W_DATABASE, T2W_TABLE, T2W_TXNID);

ALTER TABLE `TXN_TO_WRITE_ID` DROP INDEX `TBL_TO_WRITE_ID_IDX`, ADD UNIQUE INDEX `TBL_TO_WRITE_ID_IDX` (T2W_DATABASE, T2W_TABLE, T2W_WRITEID);

ALTER TABLE `TXN_COMPONENTS` DROP INDEX `TC_TXNID_INDEX`, ADD INDEX `TC_TXNID_INDEX` (TC_TXNID);

ALTER TABLE `TYPE_FIELDS` DROP INDEX `TYPE_FIELDS_N49`, ADD INDEX `TYPE_FIELDS_N49` (`TYPE_NAME`);

ALTER TABLE `FUNCS` DROP INDEX `UNIQUEFUNCTION`, ADD UNIQUE INDEX `UNIQUEFUNCTION` (`FUNC_NAME`, `DB_ID`);

ALTER TABLE `PARTITIONS` DROP INDEX `UNIQUEPARTITION`, ADD UNIQUE INDEX `UNIQUEPARTITION` (`TBL_ID`, `PART_NAME`);

ALTER TABLE `PACKAGES` DROP INDEX `UNIQUEPKG`, ADD UNIQUE INDEX `UNIQUEPKG` (NAME, DB_ID);

ALTER TABLE `STORED_PROCS` DROP INDEX `UNIQUESTOREDPROC`, ADD UNIQUE INDEX `UNIQUESTOREDPROC` (NAME, DB_ID);

ALTER TABLE `TBLS` DROP INDEX `UNIQUETABLE`, ADD UNIQUE INDEX `UNIQUETABLE` (`DB_ID`,`TBL_NAME`);

ALTER TABLE `CTLGS` DROP INDEX `UNIQUE_CATALOG`, ADD UNIQUE INDEX `UNIQUE_CATALOG` (`NAME`);

ALTER TABLE `DBS` DROP INDEX `UNIQUE_DATABASE`, ADD UNIQUE INDEX `UNIQUE_DATABASE` (`NAME`, `CTLG_NAME`);

ALTER TABLE `I_SCHEMA` DROP INDEX `UNIQUE_NAME`, ADD INDEX `UNIQUE_NAME` (`NAME`);

ALTER TABLE `SCHEDULED_EXECUTIONS` DROP INDEX `UNIQUE_SCHEDULED_EXECUTIONS_ID`, ADD UNIQUE INDEX `UNIQUE_SCHEDULED_EXECUTIONS_ID` (SCHEDULED_EXECUTION_ID);

ALTER TABLE `TYPES` DROP INDEX `UNIQUE_TYPE`, ADD UNIQUE INDEX `UNIQUE_TYPE` (`TYPE_NAME`);

ALTER TABLE `SCHEMA_VERSION` DROP INDEX `UNIQUE_VERSION`, ADD INDEX `UNIQUE_VERSION` (`SCHEMA_ID`, `VERSION`);

ALTER TABLE `WM_MAPPING` DROP INDEX `UNIQUE_WM_MAPPING`, ADD UNIQUE INDEX `UNIQUE_WM_MAPPING` (`RP_ID`, `ENTITY_TYPE`, `ENTITY_NAME`);

ALTER TABLE `WM_POOL` DROP INDEX `UNIQUE_WM_POOL`, ADD UNIQUE INDEX `UNIQUE_WM_POOL` (`RP_ID`, `PATH`);

ALTER TABLE `WM_RESOURCEPLAN` DROP INDEX `UNIQUE_WM_RESOURCEPLAN`, ADD UNIQUE INDEX `UNIQUE_WM_RESOURCEPLAN` (`NAME`, `NS`);

ALTER TABLE `WM_TRIGGER` DROP INDEX `UNIQUE_WM_TRIGGER`, ADD UNIQUE INDEX `UNIQUE_WM_TRIGGER` (`RP_ID`, `NAME`);

ALTER TABLE `ROLE_MAP` DROP INDEX `USERROLEMAPINDEX`, ADD UNIQUE INDEX `USERROLEMAPINDEX` (`PRINCIPAL_NAME`,`ROLE_ID`,`GRANTOR`,`GRANTOR_TYPE`);

