SELECT 'Upgrading MetaStore schema from 4.2.0 to 4.3.0' AS MESSAGE;

ALTER TABLE HIVE_LOCKS ADD HL_CATALOG varchar(128) NOT NULL DEFAULT 'hive';
ALTER TABLE MATERIALIZATION_REBUILD_LOCKS ADD  MRL_CAT_NAME varchar(128) NOT NULL DEFAULT 'hive';

-- Add surrogate primary keys for HA database replication. Adding AUTO_INCREMENT
-- PRIMARY KEY via ALTER TABLE rebuilds large InnoDB tables and blocks writes for
-- the duration. Rebuild each populated table via a TMP_* copy/swap instead.
-- Counter tables contain a single row and keep the one-step ALTER form. Plan a
-- maintenance window for busy metastores; duration scales with row counts.

CREATE TABLE TMP_TXN_COMPONENTS (
  TC_ID bigint NOT NULL AUTO_INCREMENT,
  TC_TXNID bigint NOT NULL,
  TC_DATABASE varchar(128) NOT NULL,
  TC_TABLE varchar(256),
  TC_PARTITION varchar(767),
  TC_OPERATION_TYPE char(1) NOT NULL,
  TC_WRITEID bigint,
  PRIMARY KEY (TC_ID),
  FOREIGN KEY (TC_TXNID) REFERENCES TXNS (TXN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
INSERT INTO TMP_TXN_COMPONENTS (TC_TXNID, TC_DATABASE, TC_TABLE, TC_PARTITION, TC_OPERATION_TYPE, TC_WRITEID)
  SELECT TC_TXNID, TC_DATABASE, TC_TABLE, TC_PARTITION, TC_OPERATION_TYPE, TC_WRITEID FROM TXN_COMPONENTS;
RENAME TABLE TXN_COMPONENTS TO TXN_COMPONENTS_OLD, TMP_TXN_COMPONENTS TO TXN_COMPONENTS;
DROP TABLE TXN_COMPONENTS_OLD;
CREATE INDEX TC_TXNID_INDEX ON TXN_COMPONENTS (TC_TXNID);

CREATE TABLE TMP_COMPLETED_TXN_COMPONENTS (
  CTC_ID bigint NOT NULL AUTO_INCREMENT,
  CTC_TXNID bigint NOT NULL,
  CTC_DATABASE varchar(128) NOT NULL,
  CTC_TABLE varchar(256),
  CTC_PARTITION varchar(767),
  CTC_TIMESTAMP timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CTC_WRITEID bigint,
  CTC_UPDATE_DELETE char(1) NOT NULL,
  PRIMARY KEY (CTC_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
INSERT INTO TMP_COMPLETED_TXN_COMPONENTS (CTC_TXNID, CTC_DATABASE, CTC_TABLE, CTC_PARTITION, CTC_TIMESTAMP, CTC_WRITEID, CTC_UPDATE_DELETE)
  SELECT CTC_TXNID, CTC_DATABASE, CTC_TABLE, CTC_PARTITION, CTC_TIMESTAMP, CTC_WRITEID, CTC_UPDATE_DELETE FROM COMPLETED_TXN_COMPONENTS;
RENAME TABLE COMPLETED_TXN_COMPONENTS TO COMPLETED_TXN_COMPONENTS_OLD, TMP_COMPLETED_TXN_COMPONENTS TO COMPLETED_TXN_COMPONENTS;
DROP TABLE COMPLETED_TXN_COMPONENTS_OLD;
CREATE INDEX COMPLETED_TXN_COMPONENTS_IDX ON COMPLETED_TXN_COMPONENTS (CTC_DATABASE, CTC_TABLE, CTC_PARTITION) USING BTREE;

CREATE TABLE TMP_COMPACTION_METRICS_CACHE (
  CMC_ID bigint NOT NULL AUTO_INCREMENT,
  CMC_DATABASE varchar(128) NOT NULL,
  CMC_TABLE varchar(256) NOT NULL,
  CMC_PARTITION varchar(767),
  CMC_METRIC_TYPE varchar(128) NOT NULL,
  CMC_METRIC_VALUE int NOT NULL,
  CMC_VERSION int NOT NULL,
  PRIMARY KEY (CMC_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
INSERT INTO TMP_COMPACTION_METRICS_CACHE (CMC_DATABASE, CMC_TABLE, CMC_PARTITION, CMC_METRIC_TYPE, CMC_METRIC_VALUE, CMC_VERSION)
  SELECT CMC_DATABASE, CMC_TABLE, CMC_PARTITION, CMC_METRIC_TYPE, CMC_METRIC_VALUE, CMC_VERSION FROM COMPACTION_METRICS_CACHE;
RENAME TABLE COMPACTION_METRICS_CACHE TO COMPACTION_METRICS_CACHE_OLD, TMP_COMPACTION_METRICS_CACHE TO COMPACTION_METRICS_CACHE;
DROP TABLE COMPACTION_METRICS_CACHE_OLD;

CREATE TABLE TMP_WRITE_SET (
  WS_ID bigint NOT NULL AUTO_INCREMENT,
  WS_DATABASE varchar(128) NOT NULL,
  WS_TABLE varchar(256) NOT NULL,
  WS_PARTITION varchar(767),
  WS_TXNID bigint NOT NULL,
  WS_COMMIT_ID bigint NOT NULL,
  WS_OPERATION_TYPE char(1) NOT NULL,
  PRIMARY KEY (WS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
INSERT INTO TMP_WRITE_SET (WS_DATABASE, WS_TABLE, WS_PARTITION, WS_TXNID, WS_COMMIT_ID, WS_OPERATION_TYPE)
  SELECT WS_DATABASE, WS_TABLE, WS_PARTITION, WS_TXNID, WS_COMMIT_ID, WS_OPERATION_TYPE FROM WRITE_SET;
RENAME TABLE WRITE_SET TO WRITE_SET_OLD, TMP_WRITE_SET TO WRITE_SET;
DROP TABLE WRITE_SET_OLD;

ALTER TABLE TXN_TO_WRITE_ID DROP INDEX TBL_TO_TXN_ID_IDX, ADD PRIMARY KEY (T2W_DATABASE, T2W_TABLE, T2W_TXNID);
ALTER TABLE NEXT_WRITE_ID DROP INDEX NEXT_WRITE_ID_IDX, ADD PRIMARY KEY (NWI_DATABASE, NWI_TABLE);

CREATE TABLE TMP_MIN_HISTORY_WRITE_ID (
  MH_ID bigint NOT NULL AUTO_INCREMENT,
  MH_TXNID bigint NOT NULL,
  MH_DATABASE varchar(128) NOT NULL,
  MH_TABLE varchar(256) NOT NULL,
  MH_WRITEID bigint NOT NULL,
  PRIMARY KEY (MH_ID),
  FOREIGN KEY (MH_TXNID) REFERENCES TXNS (TXN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
INSERT INTO TMP_MIN_HISTORY_WRITE_ID (MH_TXNID, MH_DATABASE, MH_TABLE, MH_WRITEID)
  SELECT MH_TXNID, MH_DATABASE, MH_TABLE, MH_WRITEID FROM MIN_HISTORY_WRITE_ID;
RENAME TABLE MIN_HISTORY_WRITE_ID TO MIN_HISTORY_WRITE_ID_OLD, TMP_MIN_HISTORY_WRITE_ID TO MIN_HISTORY_WRITE_ID;
DROP TABLE MIN_HISTORY_WRITE_ID_OLD;
CREATE INDEX MIN_HISTORY_WRITE_ID_IDX ON MIN_HISTORY_WRITE_ID (MH_DATABASE, MH_TABLE, MH_WRITEID);

ALTER TABLE TXN_LOCK_TBL ADD TLT_ID bigint NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;
ALTER TABLE NEXT_LOCK_ID ADD NL_ID bigint NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;
ALTER TABLE NEXT_COMPACTION_QUEUE_ID ADD NCQI_ID bigint NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;

-- These lines need to be last.  Insert any changes above.
UPDATE VERSION SET SCHEMA_VERSION='4.3.0', VERSION_COMMENT='Hive release version 4.3.0' where VER_ID=1;
SELECT 'Finished upgrading MetaStore schema from 4.2.0 to 4.3.0' AS MESSAGE;
