SELECT 'Upgrading MetaStore schema from 4.0.0 to 4.1.0' AS MESSAGE;

-- HIVE-27725
DROP INDEX TAB_COL_STATS_IDX ON TAB_COL_STATS;
CREATE INDEX TAB_COL_STATS_IDX ON TAB_COL_STATS (TBL_ID, COLUMN_NAME) USING BTREE;
ALTER TABLE TAB_COL_STATS DROP COLUMN CAT_NAME, DROP COLUMN DB_NAME, DROP COLUMN TABLE_NAME;

DROP INDEX PCS_STATS_IDX ON PART_COL_STATS;
CREATE INDEX PCS_STATS_IDX ON PART_COL_STATS (PART_ID, COLUMN_NAME) USING BTREE;
ALTER TABLE PART_COL_STATS DROP COLUMN CAT_NAME, DROP COLUMN DB_NAME, DROP COLUMN TABLE_NAME, DROP COLUMN PARTITION_NAME;

-- HIVE-28292
DROP INDEX UNIQUETABLE ON TBLS;
CREATE UNIQUE INDEX UNIQUETABLE ON TBLS (DB_ID, TBL_NAME);
DROP INDEX TBLS_N49 ON TBLS;

-- HIVE-17306
ALTER TABLE COMPLETED_TXN_COMPONENTS ADD COLUMN INV_ID INT AUTO_INCREMENT INVISIBLE PRIMARY KEY;
ALTER TABLE NEXT_COMPACTION_QUEUE_ID ADD COLUMN INV_ID INT AUTO_INCREMENT INVISIBLE PRIMARY KEY;
ALTER TABLE NEXT_LOCK_ID ADD COLUMN INV_ID INT AUTO_INCREMENT INVISIBLE PRIMARY KEY;
ALTER TABLE NEXT_WRITE_ID ADD COLUMN INV_ID INT AUTO_INCREMENT INVISIBLE PRIMARY KEY;
ALTER TABLE TXN_COMPONENTS ADD COLUMN INV_ID INT AUTO_INCREMENT INVISIBLE PRIMARY KEY;
ALTER TABLE TXN_TO_WRITE_ID ADD COLUMN INV_ID INT AUTO_INCREMENT INVISIBLE PRIMARY KEY;
ALTER TABLE WRITE_SET ADD COLUMN INV_ID INT AUTO_INCREMENT INVISIBLE PRIMARY KEY;

-- These lines need to be last.  Insert any changes above.
UPDATE VERSION SET SCHEMA_VERSION='4.1.0', VERSION_COMMENT='Hive release version 4.1.0' where VER_ID=1;
SELECT 'Finished upgrading MetaStore schema from 4.0.0 to 4.1.0' AS MESSAGE;
