SELECT 'Upgrading MetaStore schema from 4.2.0 to 4.3.0' AS MESSAGE;

ALTER TABLE HIVE_LOCKS ADD HL_CATALOG varchar(128) NOT NULL DEFAULT 'hive';
ALTER TABLE MATERIALIZATION_REBUILD_LOCKS ADD  MRL_CAT_NAME varchar(128) NOT NULL DEFAULT 'hive';

CREATE INDEX MIN_HISTORY_WRITE_ID_IDX ON MIN_HISTORY_WRITE_ID (MH_DATABASE, MH_TABLE, MH_WRITEID);

ALTER TABLE TXN_COMPONENTS ADD TC_ID bigint NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;
ALTER TABLE COMPLETED_TXN_COMPONENTS ADD CTC_ID bigint NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;
ALTER TABLE COMPACTION_METRICS_CACHE ADD CMC_ID bigint NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;
ALTER TABLE WRITE_SET ADD WS_ID bigint NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;

ALTER TABLE TXN_TO_WRITE_ID DROP INDEX TBL_TO_TXN_ID_IDX, ADD PRIMARY KEY (T2W_DATABASE, T2W_TABLE, T2W_TXNID);
ALTER TABLE NEXT_WRITE_ID DROP INDEX NEXT_WRITE_ID_IDX, ADD PRIMARY KEY (NWI_DATABASE, NWI_TABLE);
ALTER TABLE MIN_HISTORY_WRITE_ID ADD MH_ID bigint NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;

ALTER TABLE TXN_LOCK_TBL ADD TLT_ID bigint NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;
ALTER TABLE NEXT_LOCK_ID ADD NL_ID bigint NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;
ALTER TABLE NEXT_COMPACTION_QUEUE_ID ADD NCQI_ID bigint NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;

-- These lines need to be last.  Insert any changes above.
UPDATE VERSION SET SCHEMA_VERSION='4.3.0', VERSION_COMMENT='Hive release version 4.3.0' where VER_ID=1;
SELECT 'Finished upgrading MetaStore schema from 4.2.0 to 4.3.0' AS MESSAGE;
