package org.apache.hadoop.hive.metastore.utils;

import org.apache.hadoop.hive.metastore.type.MetastoreTypeInfo;
import org.apache.hadoop.hive.metastore.type.MetastoreTypeInfoParser;

import java.util.List;

public class StorageSchemaUtils {
  public static final char COMMA = ',';
  public static List<MetastoreTypeInfo> getTypeInfosFromTypeString(String columnTypeProperty) {
    return new MetastoreTypeInfoParser(columnTypeProperty).parseTypeInfos();
  }

  private static final String FROM_STORAGE_SCHEMA_READER = "generated by storage schema reader";
  public static String determineFieldComment(String comment) {
    return (comment == null) ? FROM_STORAGE_SCHEMA_READER : comment;
  }
}
