package org.apache.hadoop.hive.metastore.utils;

import org.apache.hadoop.hive.serde2.typeinfo.TypeInfo;
import org.apache.hadoop.hive.serde2.typeinfo.TypeInfoParser;

import java.util.List;

public class StorageSchemaUtils {
  public static final char COMMA = ',';
  public static List<TypeInfo> getTypeInfosFromTypeString(String columnTypeProperty) {
    return new TypeInfoParser(columnTypeProperty).parseTypeInfos();
  }

  private static final String FROM_STORAGE_SCHEMA_READER = "generated by storage schema reader";
  public static String determineFieldComment(String comment) {
    return (comment == null) ? FROM_STORAGE_SCHEMA_READER : comment;
  }
}
