SELECT '< HIVE-2989: Support creation of TableLinks >' AS ' ';
ALTER TABLE TBLS ADD COLUMN LINK_TARGET_ID BIGINT(20) DEFAULT NULL;
ALTER TABLE TBLS ADD CONSTRAINT TBLS_FK3 FOREIGN KEY (LINK_TARGET_ID) REFERENCES TBLS (TBL_ID);
