alter table `TBLS` ADD COLUMN `MM_WATERMARK_WRITE_ID` bigint(20);
alter table `TBLS` ADD COLUMN `MM_NEXT_WRITE_ID` bigint(20);

CREATE TABLE IF NOT EXISTS `TBL_WRITES`
(
  `TW_ID` BIGINT NOT NULL,
  `TBL_ID` BIGINT NOT NULL,
  `WRITE_ID` BIGINT NOT NULL,
  `STATE` CHAR(1) NOT NULL,
  `LAST_HEARTBEAT` BIGINT,
  PRIMARY KEY (`TW_ID`),
  UNIQUE KEY `UNIQUEWRITE` (`TBL_ID`,`WRITE_ID`),
  CONSTRAINT `TBL_WRITES_FK1` FOREIGN KEY (`TBL_ID`) REFERENCES `TBLS` (`TBL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
