ALTER TABLE COLUMNS_V2 MODIFY TYPE_NAME MEDIUMTEXT;
ALTER TABLE TABLE_PARAMS MODIFY PARAM_VALUE MEDIUMTEXT CHARACTER SET latin1 COLLATE latin1_bin;
ALTER TABLE SERDE_PARAMS MODIFY PARAM_VALUE MEDIUMTEXT CHARACTER SET latin1 COLLATE latin1_bin;
ALTER TABLE SD_PARAMS MODIFY PARAM_VALUE MEDIUMTEXT CHARACTER SET latin1 COLLATE latin1_bin;

ALTER TABLE TBLS MODIFY TBL_NAME varchar(256) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL;
ALTER TABLE NOTIFICATION_LOG MODIFY TBL_NAME varchar(256);
ALTER TABLE PARTITION_EVENTS MODIFY TBL_NAME varchar(256) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL;
ALTER TABLE TAB_COL_STATS MODIFY TABLE_NAME varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL;
ALTER TABLE PART_COL_STATS MODIFY TABLE_NAME varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL;
ALTER TABLE COMPLETED_TXN_COMPONENTS MODIFY CTC_TABLE varchar(256);

ALTER TABLE COLUMNS_V2 MODIFY COLUMN_NAME varchar(767) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL;
ALTER TABLE PART_COL_PRIVS MODIFY COLUMN_NAME varchar(767) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL;
ALTER TABLE TBL_COL_PRIVS MODIFY COLUMN_NAME varchar(767) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL;
ALTER TABLE SORT_COLS MODIFY COLUMN_NAME varchar(767) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL;
ALTER TABLE TAB_COL_STATS MODIFY COLUMN_NAME varchar(767) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL;
ALTER TABLE PART_COL_STATS MODIFY COLUMN_NAME varchar(767) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL;
