CREATE TABLE IF NOT EXISTS `MV_CREATION_METADATA` (
  `TBL_ID` bigint(20) NOT NULL,
  `TBL_NAME` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `LAST_TRANSACTION_INFO` mediumtext NOT NULL,
  CONSTRAINT `MV_CREATION_METADATA_FK` FOREIGN KEY (`TBL_ID`) REFERENCES `TBLS` (`TBL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE COMPLETED_TXN_COMPONENTS_NEW (
  CTC_TXNID bigint NOT NULL,
  CTC_DATABASE varchar(128) NOT NULL,
  CTC_TABLE varchar(256),
  CTC_PARTITION varchar(767),
  CTC_ID bigint NOT NULL AUTO_INCREMENT,
  CTC_TIMESTAMP timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY(CTC_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE INDEX COMPLETED_TXN_COMPONENTS_IDX2 ON COMPLETED_TXN_COMPONENTS_NEW (CTC_DATABASE, CTC_TABLE, CTC_PARTITION) USING BTREE;
INSERT INTO COMPLETED_TXN_COMPONENTS_NEW (CTC_TXNID, CTC_DATABASE, CTC_TABLE, CTC_PARTITION)
SELECT CTC_TXNID, CTC_DATABASE, CTC_TABLE, CTC_PARTITION FROM COMPLETED_TXN_COMPONENTS;
RENAME TABLE COMPLETED_TXN_COMPONENTS TO COMPLETED_TXN_COMPONENTS_BACKUP;
RENAME TABLE COMPLETED_TXN_COMPONENTS_NEW TO COMPLETED_TXN_COMPONENTS;
DROP TABLE COMPLETED_TXN_COMPONENTS_BACKUP;
