-- Table `DELEGATION_TOKENS_V2` for classes [org.apache.hadoop.hive.metastore.model.MDelegationTokenV2]
CREATE TABLE IF NOT EXISTS `DELEGATION_TOKENS_V2`
(
    `TOKEN_IDENT` VARCHAR(767) BINARY NOT NULL,
    `TOKEN` VARCHAR(767) BINARY NULL,
    `MAX_DATE` int(11) NOT NULL,
    `RENEW_DATE` int(11) NOT NULL,
    PRIMARY KEY (`TOKEN_IDENT`)
) ENGINE=INNODB DEFAULT CHARSET=latin1;

CREATE INDEX RENEW_DATE_IDX ON DELEGATION_TOKENS_V2 (RENEW_DATE);
CREATE INDEX MAX_RENEW_DATE_IDX ON DELEGATION_TOKENS_V2 (MAX_DATE, RENEW_DATE);
