#! /bin/bash
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

d=`mktemp -d /tmp/hivetest_XXXX`
for i in `find . -name Test\*\.* | grep -v svn | egrep "java$|vm$" | sed 's/.*\/Test/Test/g' | sed 's/\.java//g' | sed 's/\.vm//g' | sort`;
do 
  if [ "$i" != "TestSerDe" ]; then
    cmd="ant -lib ../../../lib -Dtestcase=$i clean-test test -logfile $d/$i.log"
    echo $cmd;
    $cmd;
  fi
done
cat $d/*.log | grep junit | egrep "Running org|Tests run"
echo Logs at $d

err=`cat $d/*.log | grep junit | egrep "Tests run|Running org" | grep -v "Failures: 0, Errors: 0" | grep -B 1 "Failures" | tr '\n' '#'`
if [ "$err" = '' ]; then
  echo "All tests passed!";
  exit 0
else
  echo "There were some failures!"
  echo $err | tr '#' '\n';
  exit 1
fi
