drop table iceberg_table;
drop table iceberg_table1;
drop table iceberg_table2;
drop table orc_table;
drop table text_table;
drop table parquet_table;
drop table avro_table;
CREATE TABLE iceberg_table(KEY STRING, VALUE STRING) PARTITIONED BY(ds STRING) STORED BY ICEBERG;
CREATE TABLE iceberg_table1(KEY STRING, VALUE STRING) PARTITIONED BY(ds STRING) STORED BY ICEBERG;
CREATE TABLE iceberg_table2(KEY STRING, VALUE STRING) PARTITIONED BY(ds STRING) STORED BY ICEBERG;
CREATE TABLE orc_table(KEY STRING, VALUE STRING) PARTITIONED BY(ds STRING) STORED as orc;
CREATE TABLE parquet_table(KEY STRING, VALUE STRING) PARTITIONED BY(ds STRING) STORED as parquet;
CREATE TABLE text_table(KEY STRING, VALUE STRING) PARTITIONED BY(ds STRING);
CREATE TABLE avro_table(KEY STRING, VALUE STRING) PARTITIONED BY(ds STRING) STORED as avro;
SHOW TABLES;
SHOW TABLES from default where `format`="iceberg";
SHOW TABLES in default where `format`="iceberg";
SHOW TABLES where `format`="iceberg";
drop table iceberg_table;
drop table iceberg_table1;
drop table iceberg_table2;
drop table orc_table;
drop table text_table;
drop table parquet_table;
drop table avro_table;

create database testdb;
drop table testdb.iceberg_table;
drop table testdb.iceberg_table1;
drop table testdb.iceberg_table2;
drop table testdb.orc_table;
drop table testdb.text_table;
drop table testdb.parquet_table;
drop table testdb.avro_table;
CREATE TABLE testdb.iceberg_table(KEY STRING, VALUE STRING) PARTITIONED BY(ds STRING) STORED BY ICEBERG;
CREATE TABLE testdb.iceberg_table1(KEY STRING, VALUE STRING) PARTITIONED BY(ds STRING) STORED BY ICEBERG;
CREATE TABLE testdb.iceberg_table2(KEY STRING, VALUE STRING) PARTITIONED BY(ds STRING) STORED BY ICEBERG;
CREATE TABLE testdb.orc_table(KEY STRING, VALUE STRING) PARTITIONED BY(ds STRING) STORED as orc;
CREATE TABLE testdb.parquet_table(KEY STRING, VALUE STRING) PARTITIONED BY(ds STRING) STORED as parquet;
CREATE TABLE testdb.text_table(KEY STRING, VALUE STRING) PARTITIONED BY(ds STRING);
CREATE TABLE testdb.avro_table(KEY STRING, VALUE STRING) PARTITIONED BY(ds STRING) STORED as avro;
SHOW TABLES from testdb where `format`="iceberg";
SHOW TABLES in testdb where `format`="iceberg";
use testdb;
SHOW TABLES;
SHOW TABLES where `format`="iceberg";
drop table testdb.iceberg_table;
drop table testdb.iceberg_table1;
drop table testdb.iceberg_table2;
drop table testdb.orc_table;
drop table testdb.text_table;
drop table testdb.parquet_table;
drop table testdb.avro_table;
drop database if exists testdb cascade;

