--
-- Licensed to the Apache Software Foundation (ASF) under one or more
-- contributor license agreements.  See the NOTICE file distributed with
-- this work for additional information regarding copyright ownership.
-- The ASF licenses this file to you under the Apache License, Version 2.0
-- (the "License"); you may not use this file except in compliance with
-- the License.  You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--
-- Oracle has no DROP INDEX IF EXISTS; this script uses plain DROP INDEX.
-- If an index is already missing, comment out its DROP line before running.
-- Update this file whenever a new upgrade script adds an index.

DROP INDEX BUCKETING_COLS_N49;
CREATE INDEX BUCKETING_COLS_N49 ON BUCKETING_COLS (SD_ID);

DROP INDEX COLUMNS_V2_N49;
CREATE INDEX COLUMNS_V2_N49 ON COLUMNS_V2 (CD_ID);

DROP INDEX COMPLETED_COMPACTIONS_RES;
CREATE INDEX COMPLETED_COMPACTIONS_RES ON COMPLETED_COMPACTIONS (CC_DATABASE,CC_TABLE,CC_PARTITION);

DROP INDEX COMPLETED_TXN_COMPONENTS_INDEX;
CREATE INDEX COMPLETED_TXN_COMPONENTS_INDEX ON COMPLETED_TXN_COMPONENTS (CTC_DATABASE, CTC_TABLE, CTC_PARTITION);

DROP INDEX CONSTRAINTS_CT_INDEX;
CREATE INDEX CONSTRAINTS_CT_INDEX ON KEY_CONSTRAINTS(CONSTRAINT_TYPE);

DROP INDEX CONSTRAINTS_PT_INDEX;
CREATE INDEX CONSTRAINTS_PT_INDEX ON KEY_CONSTRAINTS(PARENT_TBL_ID);

DROP INDEX CTLG_NAME_DBS;
CREATE INDEX CTLG_NAME_DBS ON DBS(CTLG_NAME);

DROP INDEX DATABASE_PARAMS_N49;
CREATE INDEX DATABASE_PARAMS_N49 ON DATABASE_PARAMS (DB_ID);

DROP INDEX DBPRIVILEGEINDEX;
CREATE UNIQUE INDEX DBPRIVILEGEINDEX ON DB_PRIVS (AUTHORIZER,DB_ID,PRINCIPAL_NAME,PRINCIPAL_TYPE,DB_PRIV,GRANTOR,GRANTOR_TYPE);

DROP INDEX DB_PRIVS_N49;
CREATE INDEX DB_PRIVS_N49 ON DB_PRIVS (DB_ID);

DROP INDEX DCPRIVILEGEINDEX;
CREATE UNIQUE INDEX DCPRIVILEGEINDEX ON DC_PRIVS (AUTHORIZER,NAME,PRINCIPAL_NAME,PRINCIPAL_TYPE,DC_PRIV,GRANTOR, GRANTOR_TYPE);

DROP INDEX DC_PRIVS_N49;
CREATE INDEX DC_PRIVS_N49 ON DC_PRIVS (NAME);

DROP INDEX DUMP_IDX;
CREATE INDEX DUMP_IDX ON "REPLICATION_METRICS" ("RM_DUMP_EXECUTION_ID");

DROP INDEX FUNCS_N49;
CREATE INDEX FUNCS_N49 ON FUNCS (DB_ID);

DROP INDEX FUNC_RU_N49;
CREATE INDEX FUNC_RU_N49 ON FUNC_RU (FUNC_ID);

DROP INDEX GLOBALPRIVILEGEINDEX;
CREATE UNIQUE INDEX GLOBALPRIVILEGEINDEX ON GLOBAL_PRIVS (AUTHORIZER,PRINCIPAL_NAME,PRINCIPAL_TYPE,USER_PRIV,GRANTOR,GRANTOR_TYPE);

DROP INDEX HL_TXNID_INDEX;
CREATE INDEX HL_TXNID_INDEX ON HIVE_LOCKS (HL_TXNID);

DROP INDEX IDX_RUNTIME_STATS_CREATE_TIME;
CREATE INDEX IDX_RUNTIME_STATS_CREATE_TIME ON RUNTIME_STATS(CREATE_TIME);

DROP INDEX IDX_SCHEDULED_EX_LAST_UPDATE;
CREATE INDEX IDX_SCHEDULED_EX_LAST_UPDATE ON "SCHEDULED_EXECUTIONS" ("LAST_UPDATE_TIME");

DROP INDEX IDX_SCHEDULED_EX_SQ_ID;
CREATE INDEX IDX_SCHEDULED_EX_SQ_ID ON "SCHEDULED_EXECUTIONS" ("SCHEDULED_QUERY_ID");

DROP INDEX MIN_HISTORY_LEVEL_IDX;
CREATE INDEX MIN_HISTORY_LEVEL_IDX ON MIN_HISTORY_LEVEL (MHL_MIN_OPEN_TXNID);

DROP INDEX MIN_HISTORY_WRITE_ID_IDX;
CREATE INDEX MIN_HISTORY_WRITE_ID_IDX ON MIN_HISTORY_WRITE_ID (MH_DATABASE, MH_TABLE, MH_WRITEID);

DROP INDEX NEXT_WRITE_ID_IDX;
CREATE UNIQUE INDEX NEXT_WRITE_ID_IDX ON NEXT_WRITE_ID (NWI_DATABASE, NWI_TABLE);

DROP INDEX NOTIFICATION_LOG_EVENT_ID;
CREATE UNIQUE INDEX NOTIFICATION_LOG_EVENT_ID ON NOTIFICATION_LOG(EVENT_ID);

DROP INDEX PARTITIONCOLUMNPRIVILEGEINDEX;
CREATE INDEX PARTITIONCOLUMNPRIVILEGEINDEX ON PART_COL_PRIVS (AUTHORIZER,PART_ID,"COLUMN_NAME",PRINCIPAL_NAME,PRINCIPAL_TYPE,PART_COL_PRIV,GRANTOR,GRANTOR_TYPE);

DROP INDEX PARTITIONEVENTINDEX;
CREATE INDEX PARTITIONEVENTINDEX ON PARTITION_EVENTS (PARTITION_NAME);

DROP INDEX PARTITIONS_N49;
CREATE INDEX PARTITIONS_N49 ON PARTITIONS (SD_ID);

DROP INDEX PARTITION_KEYS_N49;
CREATE INDEX PARTITION_KEYS_N49 ON PARTITION_KEYS (TBL_ID);

DROP INDEX PARTITION_KEY_VALS_N49;
CREATE INDEX PARTITION_KEY_VALS_N49 ON PARTITION_KEY_VALS (PART_ID);

DROP INDEX PARTITION_PARAMS_N49;
CREATE INDEX PARTITION_PARAMS_N49 ON PARTITION_PARAMS (PART_ID);

DROP INDEX PARTPRIVILEGEINDEX;
CREATE INDEX PARTPRIVILEGEINDEX ON PART_PRIVS (AUTHORIZER,PART_ID,PRINCIPAL_NAME,PRINCIPAL_TYPE,PART_PRIV,GRANTOR,GRANTOR_TYPE);

DROP INDEX PART_COL_PRIVS_N49;
CREATE INDEX PART_COL_PRIVS_N49 ON PART_COL_PRIVS (PART_ID);

DROP INDEX PART_PRIVS_N49;
CREATE INDEX PART_PRIVS_N49 ON PART_PRIVS (PART_ID);

DROP INDEX PCS_STATS_IDX;
CREATE INDEX PCS_STATS_IDX ON PART_COL_STATS (PART_ID,COLUMN_NAME);

DROP INDEX POLICY_IDX;
CREATE INDEX POLICY_IDX ON "REPLICATION_METRICS" ("RM_POLICY");

DROP INDEX ROLEENTITYINDEX;
CREATE UNIQUE INDEX ROLEENTITYINDEX ON ROLES (ROLE_NAME);

DROP INDEX ROLE_MAP_N49;
CREATE INDEX ROLE_MAP_N49 ON ROLE_MAP (ROLE_ID);

DROP INDEX SDS_N49;
CREATE INDEX SDS_N49 ON SDS (SERDE_ID);

DROP INDEX SDS_N50;
CREATE INDEX SDS_N50 ON SDS (CD_ID);

DROP INDEX SD_PARAMS_N49;
CREATE INDEX SD_PARAMS_N49 ON SD_PARAMS (SD_ID);

DROP INDEX SERDE_PARAMS_N49;
CREATE INDEX SERDE_PARAMS_N49 ON SERDE_PARAMS (SERDE_ID);

DROP INDEX SORT_COLS_N49;
CREATE INDEX SORT_COLS_N49 ON SORT_COLS (SD_ID);

DROP INDEX TABLECOLUMNPRIVILEGEINDEX;
CREATE INDEX TABLECOLUMNPRIVILEGEINDEX ON TBL_COL_PRIVS (AUTHORIZER,TBL_ID,"COLUMN_NAME",PRINCIPAL_NAME,PRINCIPAL_TYPE,TBL_COL_PRIV,GRANTOR,GRANTOR_TYPE);

DROP INDEX TABLEPRIVILEGEINDEX;
CREATE INDEX TABLEPRIVILEGEINDEX ON TBL_PRIVS (AUTHORIZER,TBL_ID,PRINCIPAL_NAME,PRINCIPAL_TYPE,TBL_PRIV,GRANTOR,GRANTOR_TYPE);

DROP INDEX TABLE_PARAMS_N49;
CREATE INDEX TABLE_PARAMS_N49 ON TABLE_PARAMS (TBL_ID);

DROP INDEX TAB_COL_STATS_IDX;
CREATE INDEX TAB_COL_STATS_IDX ON TAB_COL_STATS (TBL_ID, COLUMN_NAME);

DROP INDEX TBLS_N50;
CREATE INDEX TBLS_N50 ON TBLS (SD_ID);

DROP INDEX TBL_COL_PRIVS_N49;
CREATE INDEX TBL_COL_PRIVS_N49 ON TBL_COL_PRIVS (TBL_ID);

DROP INDEX TBL_PRIVS_N49;
CREATE INDEX TBL_PRIVS_N49 ON TBL_PRIVS (TBL_ID);

DROP INDEX TBL_TO_TXN_ID_IDX;
CREATE UNIQUE INDEX TBL_TO_TXN_ID_IDX ON TXN_TO_WRITE_ID (T2W_DATABASE, T2W_TABLE, T2W_TXNID);

DROP INDEX TBL_TO_WRITE_ID_IDX;
CREATE UNIQUE INDEX TBL_TO_WRITE_ID_IDX ON TXN_TO_WRITE_ID (T2W_DATABASE, T2W_TABLE, T2W_WRITEID);

DROP INDEX TC_TXNID_INDEX;
CREATE INDEX TC_TXNID_INDEX ON TXN_COMPONENTS (TC_TXNID);

DROP INDEX TXN_WRITE_NOTIFICATION_LOG_IDX;
CREATE INDEX TXN_WRITE_NOTIFICATION_LOG_IDX ON TXN_WRITE_NOTIFICATION_LOG (WNL_TXNID, WNL_DATABASE, WNL_TABLE, WNL_PARTITION);

DROP INDEX TYPE_FIELDS_N49;
CREATE INDEX TYPE_FIELDS_N49 ON TYPE_FIELDS (TYPE_NAME);

DROP INDEX UNIQUEFUNCTION;
CREATE UNIQUE INDEX UNIQUEFUNCTION ON FUNCS (FUNC_NAME, DB_ID);

DROP INDEX UNIQUEPARTITION;
CREATE UNIQUE INDEX UNIQUEPARTITION ON PARTITIONS (TBL_ID, PART_NAME);

DROP INDEX UNIQUEPKG;
CREATE UNIQUE INDEX UNIQUEPKG ON PACKAGES ("NAME", "DB_ID");

DROP INDEX UNIQUESTOREDPROC;
CREATE UNIQUE INDEX UNIQUESTOREDPROC ON STORED_PROCS ("NAME", "DB_ID");

DROP INDEX UNIQUETABLE;
CREATE UNIQUE INDEX UNIQUETABLE ON TBLS (DB_ID,TBL_NAME);

DROP INDEX UNIQUE_DATABASE;
CREATE UNIQUE INDEX UNIQUE_DATABASE ON DBS ("NAME", CTLG_NAME);

DROP INDEX UNIQUE_TABLE;
CREATE UNIQUE INDEX UNIQUE_TABLE ON MV_CREATION_METADATA ("DB_NAME", "TBL_NAME");

DROP INDEX UNIQUE_TYPE;
CREATE UNIQUE INDEX UNIQUE_TYPE ON TYPES (TYPE_NAME);

DROP INDEX UNIQUE_WM_MAPPING;
CREATE UNIQUE INDEX UNIQUE_WM_MAPPING ON WM_MAPPING (RP_ID, ENTITY_TYPE, ENTITY_NAME);

DROP INDEX UNIQUE_WM_POOL;
CREATE UNIQUE INDEX UNIQUE_WM_POOL ON WM_POOL (RP_ID, PATH);

DROP INDEX UNIQUE_WM_RESOURCEPLAN;
CREATE UNIQUE INDEX UNIQUE_WM_RESOURCEPLAN ON WM_RESOURCEPLAN (NS, "NAME");

DROP INDEX UNIQUE_WM_TRIGGER;
CREATE UNIQUE INDEX UNIQUE_WM_TRIGGER ON WM_TRIGGER (RP_ID, "NAME");

DROP INDEX USERROLEMAPINDEX;
CREATE UNIQUE INDEX USERROLEMAPINDEX ON ROLE_MAP (PRINCIPAL_NAME,ROLE_ID,GRANTOR,GRANTOR_TYPE);

