-- OCR-2541: put the TXNS transaction id generator into ordered mode.
--
-- Run once per Oracle metastore schema. Not part of the upgrade chain: clusters already at
-- schema 4.1.0 never re-run an upgrade step, and the statement needed differs depending on
-- how the schema was created, so this cannot be applied blindly.
--
-- WHY
--   Oracle defaults sequences and identity columns to NOORDER. On RAC each instance caches
--   its own block of values, so TXN_IDs stop increasing with time. The metastore relies on
--   that ordering in two places: getOpenTxnsList treats an id missing below the high water
--   mark as an open transaction, and a reader excludes every id above its own. An id issued
--   out of order therefore leaves an already committed writer above a later reader's high
--   water mark, that writer's write id is reported as still open, and the table reads empty.
--   No error is raised, so the query simply returns nothing.
--
-- WHO IS AFFECTED
--   Any Oracle metastore on a database with more than one active instance. A single instance
--   draws from one shared cache and stays ordered, so it is not exposed. Confirm with:
--
--     SELECT instance_number, instance_name, status FROM gv$instance;
--
-- COST
--   ORDER makes Oracle coordinate allocation across instances. Keep CACHE as it is: ordering
--   is what correctness depends on, and removing the cache only costs throughput. Gaps in the
--   id sequence are expected and harmless either way, because the metastore fills them.
--
-- Either statement below takes effect on the next value generated. Neither changes data, needs
-- a restart, or requires an outage, and both reverse with NOORDER. Apply in a non-production
-- schema first. Verified on 19c against a live metastore: the identity form flips ORDER_FLAG to Y
-- with CACHE unchanged, and the metastore keeps allocating ids across the change.
--
-- HOW TO RUN
--   Set metastore_owner below, then run the file. It can be run as SYSDBA or as the metastore
--   owner itself; every lookup is an ALL_* view filtered on that owner, so it does not depend on
--   who is connected. Nothing here modifies anything: the two ALTER statements are commented out,
--   and step 2 prints the one this schema needs, schema qualified, ready to copy and run.
--
--   Both ALTERs are left commented deliberately. Applying the wrong one fails outright rather than
--   doing nothing quietly, and leaving only one of them executable would remediate upgraded
--   schemas while silently skipping the fresh installs that need the other.

-- Set this to the metastore schema owner before running. Left as a placeholder on purpose: with it
-- unset, step 0 still lists the candidate schemas and steps 1 to 3 return nothing, which is a
-- visible prompt to fill it in rather than a silent empty result that looks like "nothing to do".
SET VERIFY OFF
DEFINE metastore_owner = 'CHANGE_ME'

-- Widths only. The data dictionary declares its name columns 128 characters wide, so without these
-- every row wraps over several lines and the output is hard to read.
SET LINESIZE 200 PAGESIZE 100
COLUMN owner            FORMAT A20
COLUMN sequence_owner   FORMAT A20
COLUMN table_name       FORMAT A12
COLUMN column_name      FORMAT A12
COLUMN sequence_name    FORMAT A22
COLUMN generator        FORMAT A16
COLUMN statement_to_run FORMAT A95

-- STEP 0: if the owner is not known, this lists the schemas that own a TXNS table.
SELECT owner, table_name FROM all_tables WHERE table_name = 'TXNS' ORDER BY owner;

-- STEP 1: which generator is in use. Exactly one of these returns a row.
--   case A -> a named sequence, created by upgrade-3.2.0-to-4.0.0-alpha-1
SELECT sequence_owner, sequence_name, cache_size, order_flag FROM all_sequences
  WHERE sequence_owner = UPPER('&&metastore_owner') AND sequence_name = 'TXNS_TXN_ID_SEQ';
--   case B -> an identity column, created by a fresh install of hive-schema-4.1.0
SELECT owner, table_name, column_name, sequence_name FROM all_tab_identity_cols
  WHERE owner = UPPER('&&metastore_owner') AND table_name = 'TXNS';

-- STEP 2: the statement this schema needs. One row if remediation is required, no rows if the
-- generator is already ordered. Copy the row and run it.
SELECT 'ALTER SEQUENCE ' || sequence_owner || '.TXNS_TXN_ID_SEQ ORDER;' AS statement_to_run
  FROM all_sequences
  WHERE sequence_owner = UPPER('&&metastore_owner')
    AND sequence_name = 'TXNS_TXN_ID_SEQ' AND order_flag = 'N'
UNION ALL
SELECT 'ALTER TABLE ' || i.owner
       || '.TXNS MODIFY (TXN_ID GENERATED BY DEFAULT AS IDENTITY (ORDER));'
  FROM all_tab_identity_cols i
  JOIN all_sequences s
    ON s.sequence_name = i.sequence_name AND s.sequence_owner = i.owner
  WHERE i.owner = UPPER('&&metastore_owner') AND i.table_name = 'TXNS' AND s.order_flag = 'N';

-- CASE A: named sequence.
-- ALTER SEQUENCE <owner>.TXNS_TXN_ID_SEQ ORDER;

-- CASE B: identity column.
-- The backing sequence is system generated, so ALTER SEQUENCE on it raises ORA-32793 (confirmed on
-- 19c) and the change has to go through the column instead. Do not add START WITH: the only form
-- available here is START WITH LIMIT VALUE, which restarts from the highest value currently in
-- TXNS, and TXNS is pruned continuously. Ids far above the surviving rows are still referenced by
-- TXN_TO_WRITE_ID and COMPLETED_TXN_COMPONENTS, so restarting would reissue them.
-- ALTER TABLE <owner>.TXNS MODIFY (TXN_ID GENERATED BY DEFAULT AS IDENTITY (ORDER));

-- STEP 3: verify. One row, and ORDER_FLAG must read Y. This reports the generator actually in use
-- rather than whichever case was expected, so applying the wrong statement cannot look like it
-- worked. CACHE_SIZE is expected to stay as it was; ordering is the part that matters.
SELECT 'named sequence' AS generator, sequence_name, cache_size, order_flag
  FROM all_sequences
  WHERE sequence_owner = UPPER('&&metastore_owner') AND sequence_name = 'TXNS_TXN_ID_SEQ'
UNION ALL
SELECT 'identity column', s.sequence_name, s.cache_size, s.order_flag
  FROM all_tab_identity_cols i
  JOIN all_sequences s
    ON s.sequence_name = i.sequence_name AND s.sequence_owner = i.owner
  WHERE i.owner = UPPER('&&metastore_owner') AND i.table_name = 'TXNS';
