SELECT 'Upgrading MetaStore schema from 4.2.0 to 4.3.0' AS Status from dual;

DROP INDEX COMPLETED_TXN_COMPONENTS_INDEX;
DROP INDEX COMPLETED_COMPACTIONS_RES;
DROP INDEX TBL_TO_TXN_ID_IDX;
DROP INDEX TBL_TO_WRITE_ID_IDX;
DROP INDEX NEXT_WRITE_ID_IDX;

ALTER TABLE HIVE_LOCKS ADD (HL_CATALOG VARCHAR2(128) DEFAULT 'hive' NOT NULL);
ALTER TABLE MATERIALIZATION_REBUILD_LOCKS ADD (MRL_CAT_NAME VARCHAR2(128) DEFAULT 'hive' NOT NULL);
ALTER TABLE TXN_COMPONENTS ADD (TC_CATALOG VARCHAR2(128) DEFAULT 'hive' NOT NULL);
ALTER TABLE COMPLETED_TXN_COMPONENTS ADD (CTC_CATALOG VARCHAR2(128) DEFAULT 'hive' NOT NULL);
ALTER TABLE COMPACTION_QUEUE ADD (CQ_CATALOG VARCHAR2(128) DEFAULT 'hive' NOT NULL);
ALTER TABLE COMPLETED_COMPACTIONS ADD (CC_CATALOG VARCHAR2(128) DEFAULT 'hive' NOT NULL);
ALTER TABLE COMPACTION_METRICS_CACHE ADD (CMC_CATALOG VARCHAR2(128) DEFAULT 'hive' NOT NULL);
ALTER TABLE WRITE_SET ADD (WS_CATALOG VARCHAR2(128) DEFAULT 'hive' NOT NULL);
ALTER TABLE TXN_TO_WRITE_ID ADD (T2W_CATALOG VARCHAR2(128) DEFAULT 'hive' NOT NULL);
ALTER TABLE NEXT_WRITE_ID ADD (NWI_CATALOG VARCHAR2(128) DEFAULT 'hive' NOT NULL);
ALTER TABLE MIN_HISTORY_WRITE_ID ADD (MH_CATALOG VARCHAR2(128) DEFAULT 'hive' NOT NULL);
ALTER TABLE TXN_WRITE_NOTIFICATION_LOG ADD (WNL_CATALOG VARCHAR2(128) DEFAULT 'hive' NOT NULL);

CREATE INDEX COMPLETED_TXN_COMPONENTS_INDEX ON COMPLETED_TXN_COMPONENTS (CTC_CATALOG, CTC_DATABASE, CTC_TABLE, CTC_PARTITION);
CREATE INDEX COMPLETED_COMPACTIONS_RES ON COMPLETED_COMPACTIONS (CC_CATALOG, CC_DATABASE, CC_TABLE, CC_PARTITION);
CREATE UNIQUE INDEX TBL_TO_TXN_ID_IDX ON TXN_TO_WRITE_ID (T2W_CATALOG, T2W_DATABASE, T2W_TABLE, T2W_TXNID);
CREATE UNIQUE INDEX TBL_TO_WRITE_ID_IDX ON TXN_TO_WRITE_ID (T2W_CATALOG, T2W_DATABASE, T2W_TABLE, T2W_WRITEID);
CREATE UNIQUE INDEX NEXT_WRITE_ID_IDX ON NEXT_WRITE_ID (NWI_CATALOG, NWI_DATABASE, NWI_TABLE);
CREATE INDEX MIN_HISTORY_WRITE_ID_IDX ON MIN_HISTORY_WRITE_ID (MH_CATALOG, MH_DATABASE, MH_TABLE, MH_WRITEID);

-- These lines need to be last.  Insert any changes above.
UPDATE VERSION SET SCHEMA_VERSION='4.3.0', VERSION_COMMENT='Hive release version 4.3.0' where VER_ID=1;
SELECT 'Finished upgrading MetaStore schema from 4.2.0 to 4.3.0' AS Status from dual;
