/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package org.apache.hadoop.hive.ql.plan.api;


import java.util.Set;
import java.util.HashSet;
import java.util.Collections;
import org.apache.thrift.IntRangeSet;
import java.util.Map;
import java.util.HashMap;

public class AdjacencyType {
  public static final int CONJUNCTIVE = 0;
  public static final int DISJUNCTIVE = 1;

  public static final IntRangeSet VALID_VALUES = new IntRangeSet(
    CONJUNCTIVE, 
    DISJUNCTIVE );

  public static final Map<Integer, String> VALUES_TO_NAMES = new HashMap<Integer, String>() {{
    put(CONJUNCTIVE, "CONJUNCTIVE");
    put(DISJUNCTIVE, "DISJUNCTIVE");
  }};
}
