/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "fb303_constants.h"

namespace facebook { namespace fb303 {

const fb303Constants g_fb303_constants;

fb303Constants::fb303Constants() {
}

}} // namespace

