DESCRIBE FUNCTION abs;
DESCRIBE FUNCTION acos;
DESCRIBE FUNCTION asin;
DESCRIBE FUNCTION date_add;
DESCRIBE FUNCTION parse_url;
DESCRIBE FUNCTION split;

DESCRIBE FUNCTION EXTENDED abs;
DESCRIBE FUNCTION EXTENDED acos;
DESCRIBE FUNCTION EXTENDED asin;
DESCRIBE FUNCTION EXTENDED date_add;
DESCRIBE FUNCTION EXTENDED parse_url;
DESCRIBE FUNCTION EXTENDED split;
