-- HIVE-21077
ALTER TABLE "DBS" ADD "CREATE_TIME" BIGINT;
ALTER TABLE "CTLGS" ADD "CREATE_TIME" BIGINT;

UPDATE "VERSION" SET "SCHEMA_VERSION"='3.0.1000', "VERSION_COMMENT"='Hive release version 3.0.1000' where "VER_ID"=1;
SELECT 'Finished upgrading MetaStore schema from 3.0.0 to 3.0.1000';
