-- Table structure for CHANGE_VERSION
--
CREATE TABLE "CHANGE_VERSION" (
  "CHANGE_VERSION_ID" bigint,
  "VERSION" bigint NOT NULL,
  "TOPIC" character varying(255) NOT NULL
);
--
ALTER TABLE ONLY "CHANGE_VERSION" ADD CONSTRAINT "CHANGE_VERSION_pkey" PRIMARY KEY ("CHANGE_VERSION_ID");
ALTER TABLE ONLY "CHANGE_VERSION" ADD CONSTRAINT "CHANGE_VERSION_UNIQUE" UNIQUE ("TOPIC");
