
ALTER TABLE "TBLS" ADD COLUMN "MM_WATERMARK_WRITE_ID" bigint DEFAULT -1;
ALTER TABLE "TBLS" ADD COLUMN "MM_NEXT_WRITE_ID" bigint DEFAULT 0;

CREATE TABLE "TBL_WRITES"
(
  "TW_ID" BIGINT NOT NULL,
  "TBL_ID" BIGINT NOT NULL,
  "WRITE_ID" BIGINT NOT NULL,
  "STATE" CHAR(1) NOT NULL,
  "CREATED" BIGINT NOT NULL,
  "LAST_HEARTBEAT" BIGINT NOT NULL
);
ALTER TABLE ONLY "TBL_WRITES" ADD CONSTRAINT "TBL_WRITES_PK" PRIMARY KEY ("TW_ID");
ALTER TABLE ONLY "TBL_WRITES" ADD CONSTRAINT "TBL_WRITES_FK1" FOREIGN KEY ("TBL_ID") REFERENCES "TBLS" ("TBL_ID") DEFERRABLE;
ALTER TABLE ONLY "TBL_WRITES" ADD CONSTRAINT "UNIQUEWRITE" UNIQUE ("TBL_ID", "WRITE_ID");
