UPDATE "FUNC_RU"
  SET "RESOURCE_URI" = 's3a' || SUBSTR("RESOURCE_URI", 4)
WHERE
      "RESOURCE_URI" LIKE 's3n://%'
;

UPDATE "SKEWED_COL_VALUE_LOC_MAP"
  SET "LOCATION" = 's3a' || SUBSTR("LOCATION", 4)
WHERE
      "LOCATION" LIKE 's3n://%'
;

UPDATE "SDS"
  SET "LOCATION" = 's3a' || SUBSTR("LOCATION", 4)
WHERE
      "LOCATION" LIKE 's3n://%'
;

UPDATE "DBS"
  SET "DB_LOCATION_URI" = 's3a' || SUBSTR("DB_LOCATION_URI", 4)
WHERE
      "DB_LOCATION_URI" LIKE 's3n://%'
;
