
-- Transaction related tables are below

CREATE TABLE TXNS (
  TXN_ID INT64 NOT NULL,
  TXN_STATE STRING(1) NOT NULL,
  TXN_STARTED INT64 NOT NULL,
  TXN_LAST_HEARTBEAT INT64 NOT NULL,
  TXN_USER STRING(128) NOT NULL,
  TXN_HOST STRING(128) NOT NULL,
  TXN_AGENT_INFO STRING(128),
  TXN_META_INFO STRING(128),
  TXN_HEARTBEAT_COUNT INT64
) PRIMARY KEY(TXN_ID ASC);

CREATE INDEX TXN_STATE_INDEX ON TXNS (TXN_STATE);

-- originally no primary key. But we have to add a key for Spanner
-- we have added all the not null columns
CREATE TABLE TXN_COMPONENTS (
  TC_TXNID INT64 NOT NULL,
  TC_DATABASE STRING(128) NOT NULL,
  TC_TABLE STRING(128),
  TC_PARTITION STRING(767),
  TC_OPERATION_TYPE STRING(1) NOT NULL,
  CONSTRAINT TXN_COMPONENTS_FK1 FOREIGN KEY (TC_TXNID) REFERENCES TXNS(TXN_ID),
) PRIMARY KEY(TC_DATABASE,TC_TABLE,TC_OPERATION_TYPE, TC_PARTITION, TC_TXNID ASC);

CREATE INDEX TC_TXNID_INDEX ON TXN_COMPONENTS (TC_TXNID ASC);

-- originally no primary key. But we have to add a key for Spanner
-- we have added all the not null columns
CREATE TABLE COMPLETED_TXN_COMPONENTS (
  CTC_TXNID INT64 NOT NULL,
  CTC_DATABASE STRING(128) NOT NULL,
  CTC_TABLE STRING(256),
  CTC_PARTITION STRING(767)
) PRIMARY KEY(CTC_DATABASE, CTC_TABLE, CTC_PARTITION, CTC_TXNID ASC);

CREATE TABLE NEXT_TXN_ID (
  NTXN_ID INT64 NOT NULL,
  NTXN_NEXT INT64 NOT NULL,
) PRIMARY KEY(NTXN_ID ASC);

CREATE TABLE HIVE_LOCKS (
  HL_LOCK_EXT_ID INT64 NOT NULL,
  HL_LOCK_INT_ID INT64 NOT NULL,
  HL_TXNID INT64,
  HL_DB STRING(128) NOT NULL,
  HL_TABLE STRING(128),
  HL_PARTITION STRING(767),
  HL_LOCK_STATE STRING(1) not null,
  HL_LOCK_TYPE STRING(1) not null,
  HL_LAST_HEARTBEAT INT64 NOT NULL,
  HL_ACQUIRED_AT INT64,
  HL_USER STRING(128) NOT NULL,
  HL_HOST STRING(128) NOT NULL,
  HL_HEARTBEAT_COUNT INT64,
  HL_AGENT_INFO STRING(128),
  HL_BLOCKEDBY_EXT_ID INT64,
  HL_BLOCKEDBY_INT_ID INT64,
) PRIMARY KEY(HL_LOCK_INT_ID, HL_LOCK_EXT_ID ASC);

CREATE INDEX HL_TXNID_IDX ON HIVE_LOCKS (HL_TXNID ASC);

CREATE TABLE NEXT_LOCK_ID (
  NL_ID INT64 NOT NULL,
  NL_NEXT INT64 NOT NULL,
) PRIMARY KEY(NL_ID ASC);

CREATE TABLE COMPACTION_QUEUE (
  CQ_ID INT64 NOT NULL,
  CQ_DATABASE STRING(128) NOT NULL,
  CQ_TABLE STRING(128) NOT NULL,
  CQ_PARTITION STRING(767),
  CQ_STATE STRING(1) NOT NULL,
  CQ_TYPE STRING(1) NOT NULL,
  CQ_TBLPROPERTIES STRING(2048),
  CQ_WORKER_ID STRING(128),
  CQ_START INT64,
  CQ_RUN_AS STRING(128),
  CQ_HIGHEST_TXN_ID INT64,
  CQ_META_INFO BYTES(2048),
  CQ_HADOOP_JOB_ID STRING(32)
) PRIMARY KEY(CQ_ID ASC);

CREATE TABLE COMPLETED_COMPACTIONS (
  CC_ID INT64 NOT NULL,
  CC_DATABASE STRING(128) NOT NULL,
  CC_TABLE STRING(128) NOT NULL,
  CC_PARTITION STRING(767),
  CC_STATE STRING(1) NOT NULL,
  CC_TYPE STRING(1) NOT NULL,
  CC_TBLPROPERTIES STRING(2048),
  CC_WORKER_ID STRING(128),
  CC_START INT64,
  CC_END INT64,
  CC_RUN_AS STRING(128),
  CC_HIGHEST_TXN_ID INT64,
  CC_META_INFO BYTES(2048),
  CC_HADOOP_JOB_ID STRING(32)
) PRIMARY KEY(CC_ID ASC);

CREATE TABLE NEXT_COMPACTION_QUEUE_ID (
  NCQ_ID INT64 NOT NULL,
  NCQ_NEXT INT64 NOT NULL,
) PRIMARY KEY(NCQ_ID ASC);

CREATE TABLE AUX_TABLE (
  MT_KEY1 STRING(128) NOT NULL,
  MT_KEY2 INT64 NOT NULL,
  MT_COMMENT STRING(255),
) PRIMARY KEY(MT_KEY1, MT_KEY2);

-- originally no primary key. But we have to add a key for Spanner
-- we have added all the not null columns
CREATE TABLE WRITE_SET (
  WS_DATABASE STRING(128) NOT NULL,
  WS_TABLE STRING(128) NOT NULL,
  WS_PARTITION STRING(767),
  WS_TXNID INT64 NOT NULL,
  WS_COMMIT_ID INT64 NOT NULL,
  WS_OPERATION_TYPE STRING(1) NOT NULL
) PRIMARY KEY( WS_DATABASE, WS_TABLE, WS_OPERATION_TYPE,WS_PARTITION, WS_COMMIT_ID, WS_TXNID ASC);

