FUNCTION get(CODE VARCHAR2) RETURN VARCHAR2 AS
    TMPVAR VARCHAR2(10);
  BEGIN

    TMPVAR := '';
    
    IF TRIM(TMPVAR) = '' THEN
      RETURN '00080000';
    ELSE
      RETURN TRIM(TMPVAR);
    END IF;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RETURN '00080000';
    WHEN OTHERS THEN
      RAISE;
  END;
  
get('abc');