SUBSTRING('FAILED Correct', 8);
SUBSTRING('FAILED Correct FAILED', 8, 7); 

SUBSTRING('FAILED Correct' FROM 8);
SUBSTRING('FAILED Correct FAILED' FROM 8 FOR 7); 

SUBSTRING('', 8);
SUBSTRING(NULL, 8);
