name: "Close stale pull requests"
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: This pull request has been automatically marked as
          stale because it has not had recent activity. It will be closed if
          no further activity occurs.

          Feel free to reach out on the dev@hive.apache.org list if the patch
          is in need of reviews.
        exempt-pr-labels: 'awaiting-approval,work-in-progress'
        stale-pr-label: stale
        days-before-stale: 60
        days-before-close: 7
